---
output:
  pdf_document: default
  html_document: default
---
## Activity 1:  Intro to Data Analysis and Sampling Bias

\setstretch{1}

### Learning outcomes

* Identify observational units, variables, and variable types in a statistical study. 
  
* Creating a data set

* Identify biased sampling methods.

### Terminology review
Statistics is the study of how best to collect, analyze, and draw conclusions from data.  In the next few days of class, we will learn the building blocks of the semester.  This week in class you will be introduced to the following terms:
  
* Observational units or cases

* Variables: categorical or quantitative 

* Selection bias

* Response bias

* Non-response bias

For more on these concepts, read Chapter 1 and 2 in the textbook and review the Module 1 Vocabulary Review and Key Topics.

### Notes on Observational Units and Variables {-}

\newpage

#### Review of data set {-}

In the Fall of 2025 a data set was collected on Stat 216 students in class on day 1.  The following instructions were provided to the students:

When creating a data set for use in R it is important to use single words or an underscore between words. Each outcome must be written the same way each time.  Make sure to use all lowercase letters when responding to the following questions to have consistency between responses.  Do not give units of measure for numerical values within the data set.  For `Residency` use in_state or out_state as the two outcomes. 

* Major: what is your declared major?

* Residency: do you have in-state or out-of-state residency?

* Num_Credits: how many credits are you taking this semester?

* Dominant_hand: are you left or right-handed?

* Hand_span:  what is the width of your dominant hand from the tip of your thumb to the tip of your pinky with your hand spread out measured in cm?

* Grip_dominant: what is the grip strength measured in lbs for your dominant hand?

* Grip_nondominant: what is the grip strength measured in lbs for your non-dominant hand?

The following code reads in this data set and gives a snapshot of the variables collected.  In a data set, the columns represent the variables collected on the observational units and there is one row of data for each observational unit.

```{r, echo=TRUE}
data <- read.csv("data/Fall2025_DataCollection.csv")
glimpse(data)
```

1. What are the observational units or cases for the data collected?

  \vspace{0.5in}

2. How many observations are reported in the data set? This is the **sample size**.

\vspace{0.5in}

\newpage

3. Using the glimpse of the data, fill in the following table identifying the type of each variable.

* If the variable is categorical, indicate in the third column of the following table whether the variable is binary.

* If the variable is quantitative, indicate in the forth column the units of measure used.

\begin{center}
\begin{tabular}{|l|p{1.5in}|p{0.5in}|p{0.5in}|} \hline
Column & Type of Variable & Binary? & Units? \\ \hline
Major & & &\\
& & & \\ \hline
Residency & & & \\
& & & \\ \hline
Num Credits & & & \\
& & & \\ \hline
Dominant hand & & & \\
& & & \\ \hline
Hand Span & & & \\
& & & \\ \hline
Grip strength dominant hand & & & \\
& & & \\ \hline
Grip strength non-dominant hand & & & \\
& & & \\ \hline
\end{tabular}
\end{center}

4. Review the completed data set with your class.  Remember that when creating a data set for use in R it is important to use single words or an underscore between words.  Each outcome must be written the same way each time to have consistency between responses.  Do not include units of measure in the data set when reporting numerical values.  Write down some issues found with the created class data set.

\vspace{2.5in}

### Notes on Sampling Methods and Types of bias {-}

\vspace{5in}

\newpage

#### Types of bias {-}

Complete Q5 together as a class:

5. A television station is interested in predicting whether or not local voters will pass a referendum to legalize marijuana for adult use.  The TV station asks its viewers to phone in and indicate whether they are in favor or opposed to the referendum.  Of the 2241 viewers who phoned in, forty-five percent were opposed to legalizing marijuana.
\vspace{0.1in}

    Sample size:
\vspace{0.3in}

    Observational units sampled:
\vspace{0.3in}

    Target population:
\vspace{0.3in}

    Justify why there is selection bias in this study.
\vspace{0.5in}

6. To determine if the proportion of out-of-state undergraduate students at Montana State University has increased in the last 10 years, a statistics instructor sent an email survey to 500 randomly selected current undergraduate students.  One of the questions on the survey asked whether they had in-state or out-of-state residency.  She only received 378 responses.
\vspace{0.1in}

    Sample size:
\vspace{0.3in}

    Observational units sampled:
\vspace{0.3in}

    Target population:
\vspace{0.3in}

    Justify why there is non-response bias in this study.
\vspace{0.5in}

\newpage

7. To gauge the interest of Bozeman City Voters in a new swimming pool, a local organization stood outside of the Bogert Pool in Bozeman, MT, during open hours.  One of the questions they asked was, "Since the Bogert Pool is in such bad repair, don't you agree that the city should fund a new pool?"
\vspace{0.1in}

    Sample size:
\vspace{0.3in}

    Observational units sampled:
\vspace{0.3in}

    Target population:
\vspace{0.3in}

    Justify why there is response bias in this study.
\vspace{0.5in}

    Justify why there is selection bias in this study.
\vspace{0.5in}

### Take-home messages

1. There are two types of variables: categorical (groups) and quantitative (numerical measures).

2. We will learn more about summarizing variable later in the semester.  Categorical variables are summarized by calculating a proportion from the data and quantitative variables are summarized by finding the mean and the standard deviation.

3.  There are three types of bias to be aware of when designing a sampling method: selection bias, non-response bias, and response bias.

### Additional notes

Use this space to summarize your thoughts and take additional notes on today's activity and material covered, and to write down the names and contact information of your teammates.

\newpage
