---
output:
  pdf_document: default
  html_document: default
---
# Basics of Data and Sampling Methods

## Vocabulary Review and Key Topics 

At the beginning of each module is a summary of key topics and new vocabulary terms for that module. As you read through the material in the textbook and watch the videos prior to class, look for these terms.  Reference the definitions to guide your understanding.

### Key topics

Module 1 introduces the foundations of data: observational units, types of variables, and how to collect sample data from a population of interest in a way that allows us to generalize our results back to the population.

### Vocabulary

* **Data**: observations used to answer research questions.

* **Observational units (cases)**: the subjects or entities on which data are collected.

    * The rows in a data set represent the observational units.

* **Sample size**: the number of observational units in a data set, denoted by $n$.

* **Variable**: the characteristics collected on each observational unit.

* **Types of variables**:

    * **Categorical**: cases are grouped into categories.


    * **Quantitative**: numerical measurements, where performing arithmetic operations makes sense.

* **Target population**: group of observational units of interest.

* **Sample**: subset of the population.

* **Sampling methods**:

    * **Unbiased sampling method (e.g., a random sample)**: on average, the sample will be representative of the target population; all observational units in the target population have the same chance of being selected.

    * **Biased sampling method (e.g., convenience sample)**: on average, the sample will not be representative of the target population; some part of the target population will be over- or under-represented.

* **Type of sampling bias**:

    * **Selection bias**: method of sampling is biased; some part of the target population is over- or under-represented.

    * **Non-response bias**: part of a pre-selected sample does not respond or cannot be reached.

    * **Response bias**: responses are not truthful (poor/leading question phrasing, social desirability).

* **Generalization**: to what group of observational units can the results be applied to?  

    * If an unbiased method of selection was used and there is no non-response or response bias, we can generalize the results to the target population.

    * If a biased method of selection was used or if non-response or response bias is present, we can only generalize the result to the sample or similar observational units. 

\newpage