## Guided Activity 2: American Indian Address

\setstretch{1}

### Learning outcomes

* Explain why a sampling method is unbiased or biased.

* Identify biased sampling methods.

* Explain the purpose of random selection and its effect on scope of inference.

### Terminology review

In this activity, we will examine unbiased and biased methods of sampling. Some terms covered in this activity are:


* Random sample

* Unbiased vs biased methods of selection

* Generalization


To review these concepts, see Chapter 2 in the textbook. 

### Class Preparation

Prior to the next class, complete questions 1--3.

### American Indian Address

For this activity, you will read a speech given by Jim Becenti, a member of the Navajo American Indian tribe, who spoke about the employment problems his people faced at an Office of Indian Affairs meeting in Phoenix, Arizona, on January 30, 1947 [@becentispeech]. His speech is below:

**It is hard for us to go outside the reservation where we meet strangers. I have been off the reservation ever since I was sixteen. Today I am sorry I quit the Santa Fe [Railroad]. I worked for them in 1912--13. You are enjoying life, liberty, and happiness on the soil the American Indian had, so it is your responsibility to give us a hand, brother. Take us out of distress. I have never been to vocational school. I have very little education. I look at the white man who is a skilled laborer. When I was a young man I worked for a man in Gallup as a carpenter’s helper. He treated me as his own brother. I used his tools. Then he took his tools and gave me a list of tools I should buy and I started carpentering just from what I had seen. We have no alphabetical language.**

**We see things with our eyes and can always remember it. I urge that we help my people to progress in skilled labor as well as common labor. The hope of my people is to change our ways and means in certain directions, so they can help you someday as taxpayers. If not, as you are going now, you will be burdened the rest of your life. The hope of my people is that you will continue to help so that we will be all over the United States and have a hand with you, and give us a brotherly hand so we will be happy as you are. Our reservation is awful small. We did not know the capacity of the range until the white man come and say “you raise too much sheep, got to go somewhere else,” resulting in reduction to a skeleton where the Indians can’t make a living on it. For eighty years we have been confused by the general public, and what is the condition of the Navajo today? Starvation! We are starving for education. Education is the main thing and the only thing that is going to make us able to compete with you great men here talking to us.**

#### By eye selection {-}

1. Circle ten words in Jim Becenti's speech which are a representative sample of the length of words in the entire text.  Describe your method for selecting this sample.

\vspace{0.3in}

2. Fill in the table below with your selected words from the previous question and the length of each word (number of letters/digits in the word):
\vspace{1mm}

\begin{center}
\begin{tabular}{|l|p{3in}|p{1in}|} \hline
Observation & Word & Length  \\ \hline
1 & & \\ 
& & \\ \hline
2 & & \\ 
& & \\ \hline
3 & & \\ 
& & \\ \hline
4 & & \\ 
& & \\ \hline
5 & & \\ 
& & \\ \hline
6 & & \\ 
& & \\ \hline
7 & & \\
& & \\ \hline
8 & & \\ 
& & \\ \hline
9 & & \\ 
& & \\ \hline
10 & & \\ 
& & \\ \hline
\end{tabular}
\end{center}

3.  Calculate the mean (average) word length in your selected sample.  Is this value a parameter or a statistic?   
\vspace{0.3in}

### Class Activity

1.  Report your mean word length in the Google sheet.  Your instructor will create a visualization of the distribution of results generated by your class. Draw a picture of the plot here. Include a descriptive $x$-axis label.  Report the mean and standard deviation of the data.

\vspace{2in}

<!-- A dot plot and summary statistics of the "by-eye" average word lengths from by-eye samples of size 10 from a Spring 2023 class with 82 students is provided.    -->

<!-- ```{r} -->
<!-- words <- read.csv("data/Activity2AWordLength_Section004_Sp23.csv") %>% -->
<!--     na.omit() -->

<!-- words %>% -->
<!--     summarise(favstats(Letters)) -->
<!-- words%>% -->
<!--     ggplot(aes(x = Letters))+ -->
<!--     geom_dotplot()+ -->
<!--     labs(title = "Sampling Distribution of Average Word Length",  -->
<!--          x = "Average word length", -->
<!--          y = "Frequency") + -->
<!--     theme_bw() -->

<!-- ``` -->

\newpage

The plot created in the previous question is a sampling distribution of statistics.  This sampling distribution plots the mean word length from many samples taken from the population of words. 

2. Based on the plot and summary statistics of sample mean word lengths, what is your best guess for the average word length of the population of all 359 words in the speech? 
\vspace{0.3in}


3. The true mean word length of the population of all 359 words in the speech is 3.95 letters. Is this value a parameter or a statistic?   
\vspace{0.2in}

    Where does the value of 3.95 fall in the plot given? Near the center of the distribution? In the tails of the distribution?
\vspace{0.3in}

4. If the class samples were truly representative of the population of words, what proportion of sample means in the sampling distribution would you expect to be below 3.95?
\vspace{0.5in}

5.  Using the graph in Q1, estimate the proportion of students' computed sample means that were lower than the true mean of 3.95 letters? 
\vspace{0.5in}

6.  Based on your answers to questions 4 and 5, would you say the sampling method used by the class is biased or unbiased?  Justify your answer.  
\vspace{0.5in}

7.  If the sampling method is biased, what type of sampling bias (selection, response, non-response) is present?  What is the direction of the bias, i.e., does the method tend to overestimate or underestimate the population mean word length?
\vspace{0.5in}

8.  Should we use results from our "by eye" samples to make a statement about the word length in the population of words in Becenti's address?  Why or why not?
\vspace{0.6in}

\newpage

#### Types of bias {-}

9. To determine if the proportion of out-of-state undergraduate students at Montana State University has increased in the last 10 years, a statistics instructor sent an email survey to 500 randomly selected current undergraduate students.  One of the questions on the survey asked whether they had in-state or out-of-state residency.  She only received 378 responses.
\vspace{0.1in}

    Sample size:
\vspace{0.3in}

    Observational units sampled:
\vspace{0.3in}

    Target population:
\vspace{0.3in}

    Justify why there is non-response bias in this study.
\vspace{0.5in}

10. A television station is interested in predicting whether or not local voters will pass a referendum to legalize marijuana for adult.  The TV station asks its viewers to phone in and indicate whether they are in favor or opposed to the referendum.  Of the 2241 viewers who phoned in, forty-five percent were opposed to legalizing marijuana.
\vspace{0.1in}

    Sample size:
\vspace{0.3in}

    Observational units sampled:
\vspace{0.3in}

    Target population:
\vspace{0.3in}

    Justify why there is selection bias in this study.
\vspace{0.5in}

\newpage

11. To gauge the interest of Bozeman City Voters in a new swimming pool, a local organization stood outside of the Bogart Pool in Bozeman, MT, during open hours.  One of the questions they asked was, "Since the Bogart Pool is in such bad repair, don't you agree that the city should fund a new pool?"
\vspace{0.1in}

    Sample size:
\vspace{0.3in}

    Observational units sampled:
\vspace{0.3in}

    Target population:
\vspace{0.3in}

    Justify why there is response bias in this study.
\vspace{0.5in}

    Justify why there is selection bias in this study.
\vspace{0.5in}

<!-- 12. The Bozeman school district was interested in surveying parents of students about their opinions on returning to in-person classes following the COVID-19 pandemic.  They divided the school district into 10 divisions based on location and randomly surveyed 20 households within each division.  Explain why selection bias would be present in this study design. -->
<!-- \vspace{1in} -->


### Take-home messages

1.  There are three types of bias to be aware of when designing a sampling method: selection bias, non-response bias, and response bias.

2.	When we use a biased method of selection, we will over or underestimate the parameter.

3. To see if a method is biased, we compare the distribution of the estimates to the true value. We want our estimate to be on target or unbiased.  When using unbiased methods of selection, the mean of the distribution matches or is very similar to our true parameter.

4. If the sampling method is biased, inferences made about the population based on a sample estimate will not be valid. 

### Additional notes

Use this space to summarize your thoughts and take additional notes on today's activity and material covered.

\newpage