## Unit 1 Review

### Key Topics Exam 1

#### Descriptive statistics and study design {-}

1.	Identify the observational units.

2.	Identify the types of variables (categorical or quantitative).

3.	Identify the explanatory variable (if present) and the response variable (roles of variables).

4.	Identify the appropriate type of graph and summary measure.

5. Identify if a given value is a statistic or a parameter.  Identify the appropriate notation.

6.	Identify the study design (observational study or randomized experiment).

7.	Identify the sampling method and potential types of sampling bias (non-response, response, selection).

8. Identify and interpret the summary statistic

9. Identify the target population

10. Identify the types of sampling bias (response, non-response, selection, none) 

11. Identify the type(s) of graph(s) that could be used to plot the given variable(s).

#### Hypothesis testing {-}

12. Write the parameter of interest in context of the problem.

13. State the null and alternative hypotheses in both words and notation

14.	Verify the validity condition is met to use simulation-based methods to find a p-value.

15.	Verify the validity conditions are met to use theory-based methods to find a p-value from the theoretical distribution.

16.	In a simulation-based hypothesis test, describe how to create one dot on a dotplot of the null distribution using coins, cards, or spinners. 

17.	Explain where the null distribution is centered and why.

18.	Describe and illustrate how R calculates the p-value for a simulation-based test.

19.	Describe and illustrate how R calculates the p-value for a theory-based test.

20.	Type of theoretical distribution (standard normal distribution or t-distribution with appropriate degrees of freedom) used to model the standardized statistic in a theory-based hypothesis test.

21.	Calculate and interpret the standard error of the statistic under the null using the correct formula on the Golden ticket.

22.	Calculate and interpret the appropriate standardized statistic using the correct formula on the Golden ticket.

23.	Interpret the p-value in context of the study: it is the probability of ____, assuming ____.

24.	Evaluate the p-value for strength of evidence against the null: how much evidence does the p-value provide against the null?

25.	Write a conclusion about the research question based on the p-value.

26.	Describe which features of the study impact the p-value and how.


#### Confidence intervals

27.	Describe how to simulate one bootstrapped sample using cards.

28.	Explain where the bootstrap distribution is centered and why.

29.	Find an appropriate percentile confidence interval using a bootstrap distribution from R output.

30.	Verify the validity condition is met to use simulation-based methods to find the confidence interval.

31.	Verify the validity conditions are met to use theory-based methods to calculate a confidence interval.

32.	Describe and illustrate how the bootstrap distribution is used to find the confidence interval for a given confidence level.

33.	Describe and illustrate how the standard normal distribution or t-distribution is used to find the multiplier for a given confidence level.

34.	Calculate and interpret the standard error of the statistic (not assuming the null hypothesis) using the correct formula on the Golden ticket

35.	Calculate the appropriate margin of error and confidence interval using theory-based methods.

36.	Interpret the confidence interval in context of the study.

37.	Based on the interval, what decision can you make about the null hypothesis?  Does the confidence interval agree with the results of the hypothesis test?  Justify your answer.

38.	Interpret the confidence level in context of the study.  What does “confidence” mean?

39.	Describe which features of the study have an effect on the width of the confidence interval and how.

\newpage

