## Module 7 and 8  Review - Errors, Power and EDA for Two Categorical Variables 

1. Women are considered anemic if they have a hemoglobin level of less than 12.0 g/dl. An iron supplement manufacturer reports that they can increase the level of hemoglobin by 1.5 g/dl. If the supplement does not work, there will be no change in the hemoglobin level.  The researchers believe the mean change in hemoglobin level for all women is 2 g/dl from the true mean change in hemoglobin, on average.  The manufacturer plans to use a significance level of 0.01 and hold the probability of concluding that the supplement does not increase the hemoglobin level, when really it does to 10%.  

a.  What values would we enter into the power applet to find the minimum sample size needed?

|   Null Hypothesis Value $\mu_0$:

|   Alternative Hypothesis direction:

|   True value of $\mu$:
	
|   Type I Error $\alpha$:

|	Population Std. Dev. $\sigma$:

b.  What is the desired power of the test?

\vspace{0.15in}

c.  The results from the power applet indicate a minimum sample size of 23 would be needed.  If the manufacturer used a sample size of 40, would the power of the test increase or decrease?
\vspace{0.2in}

|   What if they used a significance level of 0.05?


d.  Interpret the power of the test in context of the study.

\vspace{0.5in}

2. Two widely used antidepressants for major depressive disorder (MDD) are escitalopram and sertraline. In this study, 211 people diagnosed with MDD were recruited to participate in an eight-week trial. They were randomly assigned to receive either escitalopram or sertraline, without the inclusion of a placebo. At the end of the eight weeks, participants were evaluated using the Clinical Global Impression – Improvement scale (CGI-I). The CGI-I ranges from 1 to 7, where a score of 1-2 indicates there has been some level of improvement in the participant’s mental health. The results of the study are reported in the table and plots below.  Is there evidence of a difference in likelihood of some level of improvement for people diagnosed with MDD between those taking escitalopram and those taking sertraline? Use Escitalopram – Sertraline as the order of subtraction.

|               | Escitalopram | Sertraline |  Total   |
|---------------|--------------|------------|----------|
| Improvement   |      75      |     83     |   158    |   
| No Improvement|      29      |     24     |    53    |  
| Total         |     104      |    107     |   211    | 

```{r, echo=FALSE}
par(mfrow=c(1,2))
depression <- read.csv("depression.csv")
depression %>%
  ggplot(aes(x = drug, fill = score)) +
  geom_bar(stat = "count", position = "fill") +
  labs(title = "Segmented Bar Plot of Type of Drug by CGI-I Score for People with MDD",
       y = "Relative Frequency",
       x = "Drug",
       fill = "Score") +
  scale_fill_grey()

depression %>% # Data set piped into...
  ggplot() +   # This specifies the variables
  geom_mosaic(aes(x=product(drug), fill = score)) +  # Tell it to make a mosaic plot
  labs(title = "Mosaic Plot of of Type of Drug by CGI-I Score for People with MDD",  # Make sure to title your plot 
       x = "Drug",   # Label the x axis
       y = "") +  # Remove y axis label
  scale_fill_grey(guide = guide_legend(reverse = TRUE))  # Make figure color
```
a.	Identify the role (explanatory or response) and the type (categorical or quantitative) for the variables in this study.

\vspace{0.6in}

b.	Identify the study design (observational study or randomized experiment) for this study.

\vspace{0.4in}

c.	Identify the sampling method for this study.

\vspace{0.4in}


d. If we find evidence of a difference in likelihood of some level of improvement between the two types of drug, what is the scope of inference for this study?

\vspace{0.8in}

3. There is a very strong positive association between television sets per person in a country and the life expectancy of the people in that country, which means people in countries with lots of TVs tend to live longer.  

a.  Does this mean we can improve the life expectancy of people in developing countries by sending them lots of television sets?  Explain your answer. 

\vspace{0.7in}

b. Describe a possible confounding variable in this association.   Be sure to explain how it is a confounding variable.

\vspace{0.7in}

4. Research was carried out to explore whether the method of studying, either individually or in a group, has any significant impact on a student’s final exam performance, specifically whether they pass or fail. The data for this study were gathered from a sample of 200 undergraduate students in an Introductory Chemistry class who voluntarily participated by reporting their study habits and exam outcomes (pass or fail) after their first midterm. The results of the study are reported in the table below.  Is there evidence of an association between how undergraduate students choose to study and their exam results?  Use Group – Individual as the order of subtraction.


|            |    Group     | Individual |  Total   |
|------------|--------------|------------|----------|
| Pass       |      73      |     59     |   132    |   
| Fail       |      30      |     38     |    68    |  
| Total      |     103      |     97     |   200    | 


a.  Calculate the proportion of students that failed among those that studied in a group.  Use proper notation with appropriate subscripts.

\vspace{0.6in}

b. Calculate the proportion of students that failed among those that studied as an individual.  Use proper notation with appropriate subscripts.

\vspace{0.6in}

c. Calculate and interpret the difference in proportion of students that failed between those who studied in a group and those that studied as an individual.

\vspace{1in}

d. Calculate the relative risk of failing for students that studied in a group compared to those that studied as an individual.  

\vspace{0.8in}

e. Interpret the value in part d) as a percent change in context of the problem.


\newpage