---
output:
  pdf_document: default
  html_document: default
---
## Activity 4: American Indian Address (continued)

\setstretch{1}

### Learning outcomes

* Explain the purpose of random selection and its effect on scope of inference.

* Select a simple random sample from a finite population using a random number generator. 

* Explain why a sampling method is unbiased or biased.

* Explain the effect of sample size on sampling variability.

* Explore a sampling distribution of statistics.

### Terminology review

In today's activity, we will examine unbiased and biased methods of sampling. Some terms covered in this activity are:


* Random sample

* Unbiased vs biased methods of selection

* Generalization


To review these concepts, see Section 2.1 in the textbook. 

#### Random selection {-}

Today we will return to the American Indian Address introduced in the guided activity. Suppose instead of attempting to select a representative sample by eye (which did not work), each student used a random number generator to select a simple random sample of 10 words. A **simple random sample** relies on a random mechanism to choose a sample, without replacement, from the population, such that every sample of size 10 is equally likely to be chosen.

To use a random number generator to select a simple random sample, you first need a numbered list of all the words in the population, called a **sampling frame**. You can then generate 10 random numbers from the numbers 1 to 359 (the number of words in the population), and the chosen random numbers correspond to the chosen words in your sample.

1. Use the random number generator at https://istats.shinyapps.io/RandomNumbers/ to select a simple random sample from the population of all 359 words in the speech. 

* Set "Choose Minimum" to 1 and "Choose Maximum" to 359 to represent the 359 words in the population (the sampling frame).

* Set "How many numbers do you want to generate?" to 10 and ensure the "No" option is selected under "Sample with Replacement?" 

* Click "Generate".

\newpage

Fill in the table below with the random numbers selected and use the Becenti.csv data file found on D2L to determine each number’s corresponding word and word length (number of letters/digits in the word):

\begin{center}
\begin{tabular}{|l|l|p{1in}|} \hline
Observation & Number & Length  \\ \hline
1 & & \\ 
& & \\ \hline
2 & & \\ 
& & \\ \hline
3 & & \\ 
& & \\ \hline
4 & & \\ 
& & \\ \hline
5 & & \\ 
& & \\ \hline
6 & & \\ 
& & \\ \hline
7 & & \\
& & \\ \hline
8 & & \\ 
& & \\ \hline
9 & &\\ 
& & \\ \hline
10 & & \\ 
& & \\ \hline
\end{tabular}
\end{center}

2. Calculate the mean word length in your selected sample in question 1. Is this value a parameter or a statistic?
\vspace{0.3in}

3. Report your mean word length in the Google sheet.  Your instructor will create a visualization of the distribution of results generated by your class. Draw a picture of the plot here. Include a descriptive $x$-axis label.  Report the mean and standard deviation of the data.

\vspace{2in}

<!-- A dot plot and summary statistics of the average word lengths from random samples of size 10 from a Spring 2023 class of 82 students is provided. -->

<!-- ```{r} -->
<!-- words<-data.frame(c(3.7, 4.6, 4, 3.9, 3.7, 4.7, 4.9, 4.5, 3.6, 3.5, 3.9, 3.6, 3.1, 4.2, 3.9, 5.1,  -->
<!--                     3.1, 3.8, 4, 3.2, 5.1, 3.5, 4.9, 3.9, 4.6, 3.5, 3.5, 4.3, 4.1, 5, 3.7, 3.8,  -->
<!--                     3.7, 3.6, 3.2, 4.1, 4.4, 4.5, 3.0, 3.7, 3.7, 4.1, 4.3, 3.9, 3.1, 3.1, 4.4, 3.2,  -->
<!--                     4.5, 2.5, 3.7, 4.5, 3.8, 3.3, 3.6, 4.3, 2.9, 3.6, 4.2, 2.8, 5.5, 4.6, 5.3, 4.9, 3.9,  -->
<!--                     3.8, 3.8, 4.2, 4.3, 2.5, 3.1, 3.5, 3.7, 3.3, 5.7, 4.2, 3.3, 3.2, 2.8, 5.2, 4.1, 4.5)) -->
<!-- colnames(words)<-c("letters") -->

<!-- words%>% -->
<!--     ggplot(aes(x = letters))+ -->
<!--     geom_dotplot()+ -->
<!--     labs(title = "Sampling Distribution of Average Word Length",  -->
<!--          x = "Average word length", -->
<!--          y = "Frequency") + -->
<!--     theme_bw() -->

<!-- words %>% -->
<!--   summarise(favstats(letters)) -->
<!-- ``` -->

\newpage 

4.  Where does the value 3.95, the true mean word length, fall in the distribution given? Near the center of the distribution?  In the tails of the distribution?  Circle this value on the provided distribution.
\vspace{0.3in}

5. How does the plot given in this activity compare to the plot generated in the guided activity? 

\rgi Is the shape similar?  
\vspace{0.2in}

\rgi Is the range (smallest to largest values) similar? 

\vspace{0.2in}

\rgi Is the mean of the distribution similar? 

\vspace{0.2in}

\rgi Why didn’t everyone get the same sample mean?
\vspace{0.4in}

One set of randomly generated sample mean word lengths from a single class may not be large enough to visualize the distribution results. Let’s have a computer generate 1,000 sample mean word lengths for us.

*  Navigate to the “One Variable with Sampling” Rossman/Chance web applet: http://www.rossmanchance.com/applets/2021/sampling/OneSample.html?population=gettysburg.

*  Click "Clear" below the text box containing data from the Gettysburg address to delete that data set.

*  Download the Becenti.csv file from D2L and open the spreadsheet on your computer.

*  Copy and paste the population of word lengths (column C) into the applet from the data set provided making sure to include the header.  Click "Use Data".  Verify that the mean for the data set is 3.953 with a sample size of 359.  If these are not the values you got, check with your instructor for help with copying in the data set correctly.

*  Click the check-box for "Show Sampling Options"

*  Select 1000 for "Number of samples" and select 10 for the "Sample size".  

*  Click “Draw Samples”.

6. The plot labeled “Statistics” displays the 1,000 randomly generated sample mean word lengths (the sampling distribution). Sketch this plot below. Include a descriptive $x$-axis label and be sure to write down the provided mean and SD (standard deviation) of the distribution.
\vspace{2in}

7. What is the center value (mean) of the distribution created in question 6?
\vspace{0.3in}

8. Explain why the sampling method of using a random number generator to generate a sample is a "better" method than choosing 10 words “by eye”.
\vspace{0.8in}

9.  Is random selection an unbiased method of selection?  Explain your answer. Be sure to reference your plot from question 6.
\vspace{0.5in}


### Effect of sample size {-}

We will now consider the impact of sample size.

10. First, consider if each student had selected 100 words, instead of 10, by eye. Do you think this would make the plot from the previous activity centered on 3.95 (the true mean word length)?  Explain your answer.
\vspace{0.4in}

11. Now we will select 100 words instead of 10 words at random.

*  In the "One Variable with Sampling” Rossman/Chance web applet(http://www.rossmanchance.com/applets/2021/sampling/OneSample.html?population=gettysburg.), change the Sample size to 100.

*  Click “Draw Samples”.

The plot labeled “Statistics” displays the 1,000 randomly generated sample mean word lengths. Sketch this plot below.  Include a descriptive $x$-axis label and be sure to write down the provided mean and SD (standard deviation) of the distribution.
\vspace{2in}

12.  Compare the distribution created in question 11 to the one created in question 6.  

\rgi Is the shape similar?  
\vspace{0.2in}

\rgi Is the range (smallest to largest values) similar? 

\vspace{0.2in}

\rgi Is the mean of the distribution similar? 

\vspace{0.2in}


13. Compare the values of the standard deviation of the plots in question 11 and in question 6. Which plot shows the smallest standard deviation?
\vspace{0.4in}

14. Using the evidence from your simulations, answer the following research questions:

\rgi Does changing the sample size impact whether the sample estimates are unbiased? Explain your answer.
\vspace{0.5in}

\rgi Does changing the sample size impact the variability (spread) of sample estimates? Explain your answer
\vspace{0.5in}

15. What is the purpose of random selection of a sample from the population? 

\vspace{0.8in}

### Take-home messages

1. Random selection is an unbiased method of selection.

2. To determine if a sampling method is biased or unbiased, we compare the distribution of the estimates to the true value. We want our estimate to be on target or unbiased.  When using unbiased methods of selection, the mean of the distribution matches or is very similar to our true parameter.

3. Random selection eliminates selection bias.  However, random selection will not eliminate response or non-response bias.

4. The larger the sample size, the more similar (less variable) the statistics will be from different samples.  

5. Sample size has no impact on whether a *sampling method* is biased or not. Taking a larger sample using a biased method will still result in a sample that is not representative of the population.

### Additional notes

Use this space to summarize your thoughts and take additional notes on today's activity and material covered.

\newpage
