% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{report}
\usepackage{xcolor}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\newcounter{none} % for unnumbered tables
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{booktabs}
\usepackage{geometry}
\usepackage[none]{hyphenat}
\usepackage{titlesec}
\usepackage{longtable}
\usepackage{xcolor}
\usepackage{setspace}
\usepackage{pdfpages}

\pagestyle{plain}

%%%% Set margins
\setlength{\topmargin}{-1cm}
\addtolength{\evensidemargin}{-1cm}
\addtolength{\oddsidemargin}{-1cm}
\addtolength{\textheight}{3cm}
\addtolength{\textwidth}{2cm}

% Spacing for reading guides
\newcommand{\rgs}{\vspace{12pt}} % Vertical space
\newcommand{\rgi}{\hspace{24pt}}  % Indent

\newcommand\latexcode[1]{#1}

% Format chapter titles and spacing
\renewcommand*{\chaptername}{Module}

\titleformat{\chapter}[display]
{\bfseries\Large}
{\filleft\MakeUppercase{\chaptertitlename} \Huge\thechapter}
{3ex}
{\titlerule
\vspace{1.5ex}%
\filright}
[\vspace{1.5ex}%
\titlerule]
\titlespacing*{\chapter}{0pt}{-40pt}{20pt}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{\textbf{STAT 216 Coursepack}\\
\strut \\
\includegraphics[width=5in,height=\textheight,keepaspectratio]{images/msu-campus.jpg}}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Fall 2026\\
Montana State University}
\author{Melinda Yager\\
Jade Schmidt\\
Dr.~Mark Greenwood}
\date{}

\begin{document}
\maketitle

\newpage
\thispagestyle{empty}

This resource was developed by Melinda Yager, Jade Schmidt, and Stacey Hancock in 2021 to accompany the online textbook: Hancock, S., Carnegie, N., Meyer, E., Schmidt, J., Yager, M., and Greenwood, M. (2026). \emph{Montana State Introductory Statistics with R}. Montana State University. \url{https://mtstateintrostats.github.io/IntroStatTextbook/}.

This resource is released under a \href{https://creativecommons.org/licenses/by-nc-sa/4.0/}{Creative Commons BY-NC-SA 4.0} license unless otherwise noted.

\setcounter{tocdepth}{1}
\addtocontents{toc}{\protect\thispagestyle{empty}}
\tableofcontents
\thispagestyle{empty}

\newpage
\setcounter{page}{1}

\chapter*{Preface}\label{preface}
\addcontentsline{toc}{chapter}{Preface}

This coursepack accompanies the textbook for STAT 216: Montana State Introductory Statistics with R, which can be found at \url{https://mtstateintrostats.github.io/IntroStatTextbook/}. The syllabus for the course (including the course calendar), data sets, and links to Canvas, Gradescope, and the MSU RStudio server can be found on the course webpage: \url{https://math.montana.edu/courses/s216/}.
Other notes and review materials are linked in Canvas.

Each of the activities in this workbook is designed to target specific learning outcomes of the course, giving you practice with important statistical concepts in a group setting with instructor guidance. In addition to the in-class activities for the course, video notes are provided to aid in taking notes while you complete the required videos. Bring this workbook with you to class each class period, and take notes in the workbook as you would your own notes. A well-written completed workbook will provide an optimal study guide for exams!

All activities and labs in this coursepack will be completed during class time. Parts of each lab will be turned in on Gradescope. To aid in your understanding, read through the introduction for each activity before attending class each day.

Additional review activities for each Module are provided at the end of each Unit. These review activities will be completed during weekly review sessions throughout the semester.

STAT 216 is a 3-credit in-person course. In our experience, it takes six to nine hours per week outside of class to achieve a good grade in this class. By ``good'' we mean at least a C because a grade of D or below does not count toward fulfilling degree requirements. Many of you set your goals higher than just getting a C, and we fully support that. You need roughly nine hours per week to review past activities, read feedback on previous assignments, complete current assignments, and prepare for the next day's class. A typical week in the life of a STAT 216 student looks like:

\begin{itemize}
\tightlist
\item
  \emph{Prior to class meeting}:

  \begin{itemize}
  \tightlist
  \item
    Read assigned sections of the textbook, using the provided reading guides to take notes on the material.
  \item
    Watch the provided videos, taking notes in the coursepack.
  \item
    Read through the introduction to the day's in-class activity.
  \item
    Read through the week's homework assignment and note any questions you may have on the content.
  \end{itemize}
\item
  \emph{During class meeting}:

  \begin{itemize}
  \tightlist
  \item
    Work through the activities and labs with your classmates and instructor, taking detailed notes on your answers to each question in the activity.
  \end{itemize}
\item
  \emph{After class meeting}:

  \begin{itemize}
  \tightlist
  \item
    Complete any parts of the activity you did not complete in class.
  \item
    Review the activity solutions in the Math and Stat Center, and take notes on key points.
  \item
    Complete any remaining assigned readings videos, and quizzes for the week.
  \item
    Complete the week's homework assignment.
  \item
    Attend weekly review sessions or complete the review worksheets
  \end{itemize}
\end{itemize}

\nocite{*}

\chapter{Basics of Data and Sampling Methods}\label{basics-of-data-and-sampling-methods}

\section{Vocabulary Review and Key Topics}\label{vocabulary-review-and-key-topics}

At the beginning of each module is a summary of key topics and new vocabulary terms for that module. As you read through the material in the textbook and watch the videos prior to class, look for these terms. Reference the definitions to guide your understanding.

\subsection{Key topics}\label{key-topics}

Module 1 introduces the foundations of data: observational units, types of variables, and how to collect sample data from a population of interest in a way that allows us to generalize our results back to the population.

\subsection{Vocabulary}\label{vocabulary}

\begin{itemize}
\item
  \textbf{Data}: observations used to answer research questions.
\item
  \textbf{Observational units (cases)}: the subjects or entities on which data are collected.

  \begin{itemize}
  \tightlist
  \item
    The rows in a data set represent the observational units.
  \end{itemize}
\item
  \textbf{Sample size}: the number of observational units in a data set, denoted by \(n\).
\item
  \textbf{Variable}: the characteristics collected on each observational unit.
\item
  \textbf{Types of variables}:

  \begin{itemize}
  \item
    \textbf{Categorical}: cases are grouped into categories.
  \item
    \textbf{Quantitative}: numerical measurements, where performing arithmetic operations makes sense.
  \end{itemize}
\item
  \textbf{Target population}: group of observational units of interest.
\item
  \textbf{Sample}: subset of the population.
\item
  \textbf{Statistic}: numerical value calculated on a sample; for categorical data, a proportion is calculated, for quantitative data, the mean is calculated.
\item
  \textbf{Parameter}: numerical value of the entire population we are interested in; this is generally an unknown value.
\item
  \textbf{Sampling methods}:

  \begin{itemize}
  \item
    \textbf{Unbiased sampling method (e.g., a random sample)}: on average, the sample will be representative of the target population; all observational units in the target population have the same chance of being selected.
  \item
    \textbf{Biased sampling method (e.g., convenience sample)}: on average, the sample will not be representative of the target population; some part of the target population will be over- or under-represented.
  \end{itemize}
\item
  \textbf{Type of sampling bias}:

  \begin{itemize}
  \item
    \textbf{Selection bias}: method of sampling is biased; some part of the target population is over- or under-represented.
  \item
    \textbf{Non-response bias}: part of a pre-selected sample does not respond or cannot be reached.
  \item
    \textbf{Response bias}: responses are not truthful (poor/leading question phrasing, social desirability).
  \end{itemize}
\item
  \textbf{Generalization}: to what group of observational units can the results be applied to?

  \begin{itemize}
  \item
    If an unbiased method of selection was used and there is no non-response or response bias, we can generalize the results to the target population.
  \item
    If a biased method of selection was used or if non-response or response bias is present, we can only generalize the result to the sample or similar observational units.
  \end{itemize}
\end{itemize}

\newpage

\section{Video Notes: Intro to data and Sampling Methods}\label{video-notes-intro-to-data-and-sampling-methods}

\setstretch{1}

Read through Sections 1.1 -- 1.3 and 2.1 in the course textbook and watch the course videos prior to coming to class. Fill in the following questions to aid in your understanding of the material.

\subsection{Course Videos}\label{course-videos}

\begin{itemize}
\item
  Data\_Basics
\item
  Sampling
\end{itemize}

\subsection*{Video: Data Basics (sections 1.2.1 and 1.2.2)}\label{video-data-basics-sections-1.2.1-and-1.2.2}
\addcontentsline{toc}{subsection}{Video: Data Basics (sections 1.2.1 and 1.2.2)}

\setstretch{1.5}

Data: observations used to answer research questions

Observational unit or case: the people or things we \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ data from; in a data set, each \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ represents one observational unit.

\begin{itemize}
\tightlist
\item
  The number of observational units in a data set is called the \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
\end{itemize}

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ and is denoted by the letter \_\_\_\_\_\_\_\_\_\_\_ .

Variable: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ measured on each observational unit; in a dataset, each \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ represents one variable.

\setstretch{1}

\subsubsection*{Types of variables}\label{types-of-variables}
\addcontentsline{toc}{subsubsection}{Types of variables}

\begin{itemize}
\tightlist
\item
  Categorical variable:
\end{itemize}

\vspace{0.5in}

\setstretch{1.5}

\begin{itemize}
\tightlist
\item
  Quantitative variable:
\end{itemize}

\vspace{0.5in}

Example: Review the \texttt{loan50} data set discussed in section 1.2.1 of the textbook.

\begin{itemize}
\tightlist
\item
  Identify the sample size. Write it using proper notation.
\end{itemize}

\vspace{0.2in}

\begin{itemize}
\tightlist
\item
  What are the observational units?
\end{itemize}

\vspace{0.2in}

\begin{itemize}
\tightlist
\item
  Review Table 1.4 in section 1.2.1 of the textbook, listing the 7 variables in the \texttt{loan50} data set. Identify which variables are categorical.
\end{itemize}

\vspace{0.2in}

\begin{itemize}
\tightlist
\item
  Identify which variables are quantitative.
\end{itemize}

\vspace{0.2in}

Summary measure: the \emph{type} of number (mean/proportion/correlation/etc.) used to summarize an entire data set

\rgi Examples:

\rgi \rgi proportion of loans when the person owns a home

\vspace{0.3in}

\rgi \rgi mean (or average) interest rate

\vspace{0.3in}

\begin{itemize}
\tightlist
\item
  The summary measure (mean/proportion/correlation/etc.) and type of plot (bar plot/histogram/scatterplot/etc.) used depends on the type (categorical or quantitative) of variable(s) being summarized!
\end{itemize}

\setstretch{1}

\subsubsection*{Optional Notes: Additional Example}\label{optional-notes-additional-example}
\addcontentsline{toc}{subsubsection}{Optional Notes: Additional Example}

The Bureau of Transportation Statistics (\emph{Bureau of Transportation Statistics} 2019) collects data on all forms of public transportation. The data set seen here includes several variables collect on flights departing on a random sample of 150 US airports in December of 2019.

\vspace{1mm}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{airport }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"data/airport\_delay.csv"}\NormalTok{)}
\FunctionTok{glimpse}\NormalTok{(airport)}
\CommentTok{\#\textgreater{} Rows: 150}
\CommentTok{\#\textgreater{} Columns: 19}
\CommentTok{\#\textgreater{} $ airport             \textless{}chr\textgreater{} "ABI", "ABY", "ACV", "ACY", "ADQ", "AEX", "ALB", "\textasciitilde{}}
\CommentTok{\#\textgreater{} $ city                \textless{}chr\textgreater{} "Abilene", "Albany", "Arcata/Eureka", "Atlantic Ci\textasciitilde{}}
\CommentTok{\#\textgreater{} $ state               \textless{}chr\textgreater{} " TX", " GA", " CA", " NJ", " AK", " LA", " NY", "\textasciitilde{}}
\CommentTok{\#\textgreater{} $ airport\_name        \textless{}chr\textgreater{} " Abilene Regional", " Southwest Georgia Regional"\textasciitilde{}}
\CommentTok{\#\textgreater{} $ hub                 \textless{}chr\textgreater{} "no", "no", "no", "no", "no", "no", "no", "no", "n\textasciitilde{}}
\CommentTok{\#\textgreater{} $ international       \textless{}chr\textgreater{} "no", "no", "no", "yes", "no", "yes", "yes", "yes"\textasciitilde{}}
\CommentTok{\#\textgreater{} $ elevation\_1000      \textless{}dbl\textgreater{} 1.7906, 0.1932, 0.2223, 0.0748, 0.0787, 0.0881, 0.\textasciitilde{}}
\CommentTok{\#\textgreater{} $ latitude            \textless{}dbl\textgreater{} 32.4, 31.5, 41.0, 39.5, 57.7, 31.3, 42.7, 35.2, 45\textasciitilde{}}
\CommentTok{\#\textgreater{} $ longitude           \textless{}dbl\textgreater{} {-}99.7, {-}81.2, {-}124.1, {-}74.6, {-}152.5, {-}92.5, {-}73.8,\textasciitilde{}}
\CommentTok{\#\textgreater{} $ arr\_flights         \textless{}int\textgreater{} 195, 81, 215, 293, 54, 282, 943, 410, 53, 32314, 6\textasciitilde{}}
\CommentTok{\#\textgreater{} $ perc\_delay15        \textless{}dbl\textgreater{} 16.410256, 13.580247, 23.255814, 15.358362, 12.962\textasciitilde{}}
\CommentTok{\#\textgreater{} $ perc\_cancelled      \textless{}dbl\textgreater{} 0.5128205, 0.0000000, 4.1860465, 0.6825939, 14.814\textasciitilde{}}
\CommentTok{\#\textgreater{} $ perc\_diverted       \textless{}dbl\textgreater{} 0.00000000, 0.00000000, 2.32558139, 0.68259386, 0.\textasciitilde{}}
\CommentTok{\#\textgreater{} $ arr\_delay           \textless{}int\textgreater{} 1563, 1244, 4763, 2905, 329, 1293, 15127, 9705, 25\textasciitilde{}}
\CommentTok{\#\textgreater{} $ carrier\_delay       \textless{}int\textgreater{} 459, 890, 1613, 476, 180, 302, 5627, 2253, 439, 10\textasciitilde{}}
\CommentTok{\#\textgreater{} $ weather\_delay       \textless{}int\textgreater{} 21, 43, 549, 124, 1, 58, 2346, 168, 1236, 13331, 2\textasciitilde{}}
\CommentTok{\#\textgreater{} $ nas\_delay           \textless{}int\textgreater{} 257, 39, 154, 771, 51, 112, 2096, 616, 746, 45674,\textasciitilde{}}
\CommentTok{\#\textgreater{} $ security\_delay      \textless{}int\textgreater{} 0, 0, 0, 25, 0, 0, 44, 0, 0, 375, 0, 83, 0, 23, 0,\textasciitilde{}}
\CommentTok{\#\textgreater{} $ late\_aircraft\_delay \textless{}int\textgreater{} 826, 272, 2447, 1509, 97, 821, 5014, 6668, 108, 10\textasciitilde{}}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  What are the observational units?
\end{itemize}

\vspace{0.2in}

\begin{itemize}
\tightlist
\item
  Identify which variables are categorical.
\end{itemize}

\vspace{0.2in}

\begin{itemize}
\tightlist
\item
  Identify which variables are quantitative.
\end{itemize}

\vspace{0.2in}

\subsection*{Video: Sampling (section 2.1)}\label{video-sampling-section-2.1}
\addcontentsline{toc}{subsection}{Video: Sampling (section 2.1)}

\setstretch{1.5}

The method used to collect data will impact \textbf{who the results apply to} and \textbf{what type of conclusions} can be drawn.

\begin{itemize}
\item
  Target population: all \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ of interest
\item
  Sample: the group of \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ from which data is collected; a subset of the target population
\end{itemize}

\setstretch{1}

\subsubsection*{Parameters and statistics}\label{parameters-and-statistics}
\addcontentsline{toc}{subsubsection}{Parameters and statistics}

\setstretch{1.5}

Statistic: a single number which summarizes data from a \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_; also called the \textbf{point estimate}

\begin{itemize}
\tightlist
\item
  The value of the statistic will \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ from one sample to the next, called the \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
\end{itemize}

Parameter: a single number which summarizes data from a \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

\begin{itemize}
\item
  The value of the parameter is \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_, but is typically \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
\item
  We estimate the value of the parameter by calculating a \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
\end{itemize}

\subsubsection*{Good vs.~bad sampling}\label{good-vs.-bad-sampling}
\addcontentsline{toc}{subsubsection}{Good vs.~bad sampling}

GOAL: to have a sample that is \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ of the \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ on the variable(s) of interest

\begin{itemize}
\tightlist
\item
  If the sample is \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_, then it is reasonable to believe the value of the \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ will be close to the value of the \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_!
\end{itemize}

\setstretch{1}

\begin{itemize}
\tightlist
\item
  Biased sampling method:
\end{itemize}

\vspace{0.5in}

\subsection*{Types of Sampling Bias}\label{types-of-sampling-bias}
\addcontentsline{toc}{subsection}{Types of Sampling Bias}

\begin{itemize}
\tightlist
\item
  Selection bias:
\end{itemize}

\vspace{0.5in}

Example of Selection Bias: Newspaper article from 1936 reported that Landon won the presidential election over Roosevelt based on a poll of 10 million voters. Roosevelt was the actual winner. What was wrong with this poll? Poll was completed using a telephone survey and not all people in 1936 had a telephone. Only a certain subset of the population owned a telephone so this subset was over-represented in the telephone survey. The results of the study, showing that Landon would win, did not represent the target population of all US voters.

\begin{itemize}
\tightlist
\item
  Non-response bias:
\end{itemize}

\vspace{0.5in}

\begin{itemize}
\tightlist
\item
  To calculate the non-response rate:
\end{itemize}

\[\frac{\text{number of people who do not respond}}{\text{total number of people selected for the sample}}\times 100\%\]

\begin{itemize}
\tightlist
\item
  For non-response bias to occur must first select people to participate and then they choose not to.
\end{itemize}

Example of Non-response bias: A company randomly selects buyers to complete a review of an online purchase but some choose not to respond.

\begin{itemize}
\tightlist
\item
  Response bias:
\end{itemize}

\vspace{0.5in}

Example of Response Bias: Police officer pulls you over and asks if you have been drinking. Expect people to say no, whether they have been drinking or not.

\begin{itemize}
\tightlist
\item
  Need to be able to predict how people will respond.
\end{itemize}

Words of caution:

\begin{itemize}
\tightlist
\item
  Convenience samples: gathering data for those who are easily accessible; online polls
\end{itemize}

\setstretch{1.5}

\rgi \rgi Selection bias?

\rgi \rgi Non-response bias?

\rgi \rgi Response bias?

\begin{itemize}
\tightlist
\item
  Random sampling reduces \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ bias, but has no impact on \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ or \_\_\_\_\_\_\_\_\_\_\_\_\_\_ bias.
\end{itemize}

\setstretch{1}

\begin{itemize}
\tightlist
\item
  Unbiased sample methods:
\end{itemize}

\vspace{0.5in}

\rgi \rgi Simple random sample

\subsubsection*{Optional Notes: Additional Examples}\label{optional-notes-additional-examples}
\addcontentsline{toc}{subsubsection}{Optional Notes: Additional Examples}

Many high schools moved to partial or fully online schooling in Spring of 2020. Did students who graduated in 2020 tend to have a lower GPA during freshman year of college than the previous class of college freshmen? A nationally representative sample of 1000 college students who were freshmen in AY19-20 and 1000 college students who were freshmen in AY20-21 was taken to answer this question.

\begin{itemize}
\tightlist
\item
  What is the target population?
\end{itemize}

\vspace{0.2in}

\begin{itemize}
\tightlist
\item
  What is the sample?
\end{itemize}

\vspace{0.2in}

\newpage

Discuss whether any type(s) of bias would be present for each of the data collection methods described below:

A radio talk show asks people to phone in their views on whether the United States should pay off its debt to the United Nations.

\begin{itemize}
\tightlist
\item
  Selection?
\end{itemize}

\vspace{0.25in}

\begin{itemize}
\tightlist
\item
  Non-response?
\end{itemize}

\vspace{0.25in}

\begin{itemize}
\tightlist
\item
  Response?
\end{itemize}

\vspace{0.25in}

The Wall Street Journal plans to make a prediction for the US presidential election based on a survey of its readers and plans to follow-up to ensure everyone responds.

\begin{itemize}
\tightlist
\item
  Selection?
\end{itemize}

\vspace{0.25in}

\begin{itemize}
\tightlist
\item
  Non-response?
\end{itemize}

\vspace{0.25in}

\begin{itemize}
\tightlist
\item
  Response?
\end{itemize}

\vspace{0.25in}

A police detective interested in determining the extent of drug use by high school students, randomly selects a sample of high school students and interviews each one about any illegal drug use by the student during the past year.

\begin{itemize}
\tightlist
\item
  Selection?
\end{itemize}

\vspace{0.25in}

\begin{itemize}
\tightlist
\item
  Non-response?
\end{itemize}

\vspace{0.25in}

\begin{itemize}
\tightlist
\item
  Response?
\end{itemize}

\vspace{0.25in}

\subsection{Concept Check}\label{concept-check}

Be prepared for group discussion in the next class. One member from the table should write the answers to the following on the whiteboard.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  What are the two types of variables?
\end{enumerate}

\vspace{0.3in}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\item
  Purpose of random selection:
  \vspace{0.6in}
\item
  Types of sampling bias:
\end{enumerate}

\vspace{0.5in}

\newpage

\section{Activity 1: Intro to Data Analysis and Sampling Bias}\label{activity-1-intro-to-data-analysis-and-sampling-bias}

\setstretch{1}

\subsection{Learning outcomes}\label{learning-outcomes}

\begin{itemize}
\item
  Identify observational units, variables, and variable types in a statistical study.
\item
  Creating a data set
\item
  Identify biased sampling methods.
\end{itemize}

\subsection{Terminology review}\label{terminology-review}

Statistics is the study of how best to collect, analyze, and draw conclusions from data. In the next few days of class, we will learn the building blocks of the semester. This week in class you will be introduced to the following terms:

\begin{itemize}
\item
  Observational units or cases
\item
  Variables: categorical or quantitative
\item
  Selection bias
\item
  Response bias
\item
  Non-response bias
\end{itemize}

For more on these concepts, read Chapter 1 and 2 in the textbook and review the Module 1 Vocabulary Review and Key Topics.

\subsubsection*{Notes on Observational Units and Variables}\label{notes-on-observational-units-and-variables}
\addcontentsline{toc}{subsubsection}{Notes on Observational Units and Variables}

\newpage

\subsubsection*{Review of data set}\label{review-of-data-set}
\addcontentsline{toc}{subsubsection}{Review of data set}

In the Fall of 2025 a data set was collected on Stat 216 students in class on day 1. The following instructions were provided to the students:

When creating a data set for use in R it is important to use single words or an underscore between words. Each outcome must be written the same way each time. Make sure to use all lowercase letters when responding to the following questions to have consistency between responses. Do not give units of measure for numerical values within the data set. For \texttt{Residency} use in\_state or out\_state as the two outcomes.

\begin{itemize}
\item
  Major: what is your declared major?
\item
  Residency: do you have in-state or out-of-state residency?
\item
  Num\_Credits: how many credits are you taking this semester?
\item
  Dominant\_hand: are you left or right-handed?
\item
  Hand\_span: what is the width of your dominant hand from the tip of your thumb to the tip of your pinky with your hand spread out measured in cm?
\item
  Grip\_dominant: what is the grip strength measured in lbs for your dominant hand?
\item
  Grip\_nondominant: what is the grip strength measured in lbs for your non-dominant hand?
\end{itemize}

The following code reads in this data set and gives a snapshot of the variables collected. In a data set, the columns represent the variables collected on the observational units and there is one row of data for each observational unit.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"data/Fall2025\_DataCollection.csv"}\NormalTok{)}
\FunctionTok{glimpse}\NormalTok{(data)}
\CommentTok{\#\textgreater{} Rows: 875}
\CommentTok{\#\textgreater{} Columns: 7}
\CommentTok{\#\textgreater{} $ Major                   \textless{}chr\textgreater{} "Microbiology ", "Psychology ", "Business ", "\textasciitilde{}}
\CommentTok{\#\textgreater{} $ Residency               \textless{}chr\textgreater{} "in state", "In state", "Out of state", "Out o\textasciitilde{}}
\CommentTok{\#\textgreater{} $ Num\_Credits             \textless{}chr\textgreater{} "15", "19", "17", "16", "15", "18", "16", "15"\textasciitilde{}}
\CommentTok{\#\textgreater{} $ Dominant\_hand           \textless{}chr\textgreater{} "right", "right", "right", "right", "right", "\textasciitilde{}}
\CommentTok{\#\textgreater{} $ Hand\_Span               \textless{}chr\textgreater{} "8in", "17.5 cm", "22.25", "21 cm", "19", "22"\textasciitilde{}}
\CommentTok{\#\textgreater{} $ GripStrength\_DomHand    \textless{}chr\textgreater{} "53.7", "54 lbs", "64", "88.3", "44.4", "86.4"\textasciitilde{}}
\CommentTok{\#\textgreater{} $ GripStrength\_NonDomHand \textless{}chr\textgreater{} "45.4", "32.4 lbs ", "68", "84.4", "42.2", "70\textasciitilde{}}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  What are the observational units or cases for the data collected?
\end{enumerate}

\vspace{0.5in}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  How many observations are reported in the data set? This is the \textbf{sample size}.
\end{enumerate}

\vspace{0.5in}

\newpage

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Using the glimpse of the data, fill in the following table identifying the type of each variable.
\end{enumerate}

\begin{itemize}
\item
  If the variable is categorical, indicate in the third column of the following table whether the variable is binary.
\item
  If the variable is quantitative, indicate in the forth column the units of measure used.
\end{itemize}

\begin{center}
\begin{tabular}{|l|p{1.5in}|p{0.5in}|p{0.5in}|} \hline
Column & Type of Variable & Binary? & Units? \\ \hline
Major & & &\\
& & & \\ \hline
Residency & & & \\
& & & \\ \hline
Num Credits & & & \\
& & & \\ \hline
Dominant hand & & & \\
& & & \\ \hline
Hand Span & & & \\
& & & \\ \hline
Grip strength dominant hand & & & \\
& & & \\ \hline
Grip strength non-dominant hand & & & \\
& & & \\ \hline
\end{tabular}
\end{center}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  Review the completed data set with your class. Remember that when creating a data set for use in R it is important to use single words or an underscore between words. Each outcome must be written the same way each time to have consistency between responses. Do not include units of measure in the data set when reporting numerical values. Write down some issues found with the created class data set.
\end{enumerate}

\vspace{2.5in}

\subsubsection*{Notes on Sampling Methods and Types of bias}\label{notes-on-sampling-methods-and-types-of-bias}
\addcontentsline{toc}{subsubsection}{Notes on Sampling Methods and Types of bias}

\vspace{5in}

\newpage

\subsubsection*{Types of bias}\label{types-of-bias}
\addcontentsline{toc}{subsubsection}{Types of bias}

Complete Q5 together as a class:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{4}
\item
  A television station is interested in predicting whether or not local voters will pass a referendum to legalize marijuana for adult use. The TV station asks its viewers to phone in and indicate whether they are in favor or opposed to the referendum. Of the 2241 viewers who phoned in, forty-five percent were opposed to legalizing marijuana.
  \vspace{0.1in}

  Sample size:
  \vspace{0.3in}

  Observational units sampled:
  \vspace{0.3in}

  Target population:
  \vspace{0.3in}

  Justify why there is selection bias in this study.
  \vspace{0.5in}
\item
  To determine if the proportion of out-of-state undergraduate students at Montana State University has increased in the last 10 years, a statistics instructor sent an email survey to 500 randomly selected current undergraduate students. One of the questions on the survey asked whether they had in-state or out-of-state residency. She only received 378 responses.
  \vspace{0.1in}

  Sample size:
  \vspace{0.3in}

  Observational units sampled:
  \vspace{0.3in}

  Target population:
  \vspace{0.3in}

  Justify why there is non-response bias in this study.
  \vspace{0.5in}
\end{enumerate}

\newpage

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{6}
\item
  To gauge the interest of Bozeman City Voters in a new swimming pool, a local organization stood outside of the Bogert Pool in Bozeman, MT, during open hours. One of the questions they asked was, ``Since the Bogert Pool is in such bad repair, don't you agree that the city should fund a new pool?''
  \vspace{0.1in}

  Sample size:
  \vspace{0.3in}

  Observational units sampled:
  \vspace{0.3in}

  Target population:
  \vspace{0.3in}

  Justify why there is response bias in this study.
  \vspace{0.5in}

  Justify why there is selection bias in this study.
  \vspace{0.5in}
\end{enumerate}

\subsection{Take-home messages}\label{take-home-messages}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  There are two types of variables: categorical (groups) and quantitative (numerical measures).
\item
  We will learn more about summarizing variables later in the semester. Categorical variables are summarized by calculating a proportion from the data and quantitative variables are summarized by finding the mean and the standard deviation (more later on this).
\item
  There are three types of bias to be aware of when designing a sampling method: selection bias, non-response bias, and response bias.
\end{enumerate}

\subsection{Additional notes}\label{additional-notes}

For more practice on types of bias, as well as identifying the observational units and variable(s) in a study, use the Module 1 Review worksheet in the Unit 1 Review Materials (pgs.108--109).

Use this space to summarize your thoughts and take additional notes on today's activity and material covered, and to write down the names and contact information of your teammates.

\newpage

\section{Activity 2: American Indian Address}\label{activity-2-american-indian-address}

\setstretch{1}

\subsection{Learning outcomes}\label{learning-outcomes-1}

\begin{itemize}
\item
  Explain why a sampling method is unbiased or biased.
\item
  Identify biased sampling methods.
\item
  Explain the purpose of random selection and its effect on generalization.
\end{itemize}

\subsection{Terminology review}\label{terminology-review-1}

In this activity, we will examine unbiased and biased methods of sampling. Some terms covered in this activity are:

\begin{itemize}
\item
  Random sample
\item
  Unbiased vs biased methods of selection
\item
  Generalization
\end{itemize}

To review these concepts, see Chapter 2 in the textbook.

\subsection{Class Preparation}\label{class-preparation}

Prior to the next class, complete questions 1--3.

\subsection*{American Indian Address}\label{american-indian-address}
\addcontentsline{toc}{subsection}{American Indian Address}

For this activity, you will read a speech given by Jim Becenti, a member of the Navajo American Indian tribe, who spoke about the employment problems his people faced at an Office of Indian Affairs meeting in Phoenix, Arizona, on January 30, 1947 (Moquin and Van Doren 1973). His speech is below:

\textbf{It is hard for us to go outside the reservation where we meet strangers. I have been off the reservation ever since I was sixteen. Today I am sorry I quit the Santa Fe {[}Railroad{]}. I worked for them in 1912--13. You are enjoying life, liberty, and happiness on the soil the American Indian had, so it is your responsibility to give us a hand, brother. Take us out of distress. I have never been to vocational school. I have very little education. I look at the white man who is a skilled laborer. When I was a young man I worked for a man in Gallup as a carpenter's helper. He treated me as his own brother. I used his tools. Then he took his tools and gave me a list of tools I should buy and I started carpentering just from what I had seen. We have no alphabetical language.}

\textbf{We see things with our eyes and can always remember it. I urge that we help my people to progress in skilled labor as well as common labor. The hope of my people is to change our ways and means in certain directions, so they can help you someday as taxpayers. If not, as you are going now, you will be burdened the rest of your life. The hope of my people is that you will continue to help so that we will be all over the United States and have a hand with you, and give us a brotherly hand so we will be happy as you are. Our reservation is awful small. We did not know the capacity of the range until the white man come and say ``you raise too much sheep, got to go somewhere else,'' resulting in reduction to a skeleton where the Indians can't make a living on it. For eighty years we have been confused by the general public, and what is the condition of the Navajo today? Starvation! We are starving for education. Education is the main thing and the only thing that is going to make us able to compete with you great men here talking to us.}

\subsubsection*{By eye selection}\label{by-eye-selection}
\addcontentsline{toc}{subsubsection}{By eye selection}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Circle ten words in Jim Becenti's speech which are a representative sample of the length of words in the entire text. Describe your method for selecting this sample.
\end{enumerate}

\vspace{0.7in}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Fill in the table below with your selected words from the previous question and the length of each word (number of letters/digits in the word):
  \vspace{1mm}
\end{enumerate}

\begin{center}
\begin{tabular}{|l|p{3in}|p{1in}|} \hline
Observation & Word & Length  \\ \hline
1 & & \\ 
& & \\ \hline
2 & & \\ 
& & \\ \hline
3 & & \\ 
& & \\ \hline
4 & & \\ 
& & \\ \hline
5 & & \\ 
& & \\ \hline
6 & & \\ 
& & \\ \hline
7 & & \\
& & \\ \hline
8 & & \\ 
& & \\ \hline
9 & & \\ 
& & \\ \hline
10 & & \\ 
& & \\ \hline
\end{tabular}
\end{center}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Calculate the mean (average) word length in your selected sample. Is this value a parameter or a statistic?\\
  \vspace{0.3in}
\end{enumerate}

\subsection*{Notes on sampling}\label{notes-on-sampling}
\addcontentsline{toc}{subsection}{Notes on sampling}

\vspace{5in}

\subsection{Class Activity}\label{class-activity}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Report your mean word length from question 3 to your instructor. Your instructor will create a visualization of the distribution of results generated by your class. Draw a picture of the plot here. Include a descriptive \(x\)-axis label. Report the mean and standard deviation of the sample mean word lengths.
\end{enumerate}

\vspace{2in}

\newpage

The plot created in question 1 is a sampling distribution of statistics. This sampling distribution plots the mean word length from many samples taken from the population of words.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\item
  The true mean word length of the population of all 359 words in the speech is 3.95 letters. Is this value a parameter or a statistic?\\
  \vspace{0.2in}

  Where does the value of 3.95 fall in the plot given? Near the center of the distribution? In the tails of the distribution?
  \vspace{0.3in}
\item
  Would you say the sampling method used (``by-eye'' selection) by the class is biased or unbiased? Justify your answer.\\
  \vspace{0.5in}
\item
  If the sampling method is biased, what type of sampling bias (selection, response, non-response) is present? What is the direction of the bias, i.e., does the method tend to overestimate or underestimate the population mean word length?
  \vspace{0.5in}
\end{enumerate}

\subsubsection*{Random selection}\label{random-selection}
\addcontentsline{toc}{subsubsection}{Random selection}

Suppose instead of attempting to select a representative sample by eye (which did not work), each student used a random number generator to select a simple random sample of 10 words. A \textbf{simple random sample} relies on a random mechanism to choose a sample, without replacement, from the population, such that every sample of size 10 is equally likely to be chosen.

Later in the semester we will learn more about how to use R - for today we will have a short introduction using the \texttt{R} studio server. Download the provided R script file from canvas.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  Login to the R studio server using your netID login. Upload the file to the server using the following instructions.
\end{enumerate}

\begin{itemize}
\item
  Click ``Upload'' in the ``Files'' tab in the bottom right window of RStudio. In the pop-up window, click ``Choose File'', and navigate to the folder where the Activity R script file is saved (most likely in your downloads folder). Click ``Open''; then click ``Ok''.
\item
  Once the file is uploaded, you should see the uploaded file appear in the list of files in the bottom right window. Click on the R script file name to open the file in the Editor window (upper left window).
\end{itemize}

The following code will take a random sample of 10 words from the population of 359 words.

\begin{itemize}
\tightlist
\item
  In the R script file, highlight and run lines 1--7
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sample}\NormalTok{(words}\SpecialCharTok{$}\NormalTok{Word, }\DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\newpage

Fill in the table with the random words selected and calculate the word length (number of letters/digits in the word):

\begin{center}
\begin{tabular}{|p{2.5in}|p{1in}|} \hline
Word  & Length  \\ \hline
 & \\ 
 & \\ \hline
 & \\ 
 & \\ \hline
 & \\ 
 & \\ \hline
 & \\ 
 & \\ \hline
 & \\ 
 & \\ \hline
 & \\ 
 & \\ \hline
 & \\
 & \\ \hline
 & \\ 
 & \\ \hline
 & \\ 
 & \\ \hline
 & \\ 
 & \\ \hline
\end{tabular}
\end{center}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{5}
\item
  Calculate the mean word length in your selected sample above. Is this value a parameter or a statistic?
  \vspace{0.3in}
\item
  Report your mean word length as instructed. Your instructor will create a visualization of the distribution of results generated by your class. Draw a picture of the plot here. Include a descriptive \(x\)-axis label. Report the mean and standard deviation of the samples.
\end{enumerate}

\vspace{2.5in}

One set of randomly generated sample mean word lengths from a single class may not be large enough to visualize the distribution results.

\newpage

The following is a plot of 1000 random samples of size 10 created in \texttt{R}. To re-create this plot run lines 11--28 in the \texttt{R} script file.

\begin{center}\includegraphics[width=0.65\linewidth]{01-A02-samplingbias_files/figure-latex/unnamed-chunk-3-1} \end{center}

It would be useful to know what the center (mean) is for this sampling distribution. The distribution you created in the \texttt{R} script file may vary a little from what is reported in your coursepack. To find the mean and standard deviation from your distribution run lines 32--33.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(srs\_means)}
\CommentTok{\#\textgreater{} [1] 3.9714}
\FunctionTok{sd}\NormalTok{(srs\_means)}
\CommentTok{\#\textgreater{} [1] 0.7223599}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{7}
\tightlist
\item
  Would you say this sampling method used (random selection) is biased or unbiased? Justify your answer.\\
  \vspace{0.5in}
\end{enumerate}

The following two plots show the sampling distribution of convenience samples of size 10 from the population of word length (top) and the simple random sample created above (bottom).

\begin{center}\includegraphics[width=0.7\linewidth]{01-A02-samplingbias_files/figure-latex/unnamed-chunk-5-1} \end{center}

The mean and standard deviation for the convenience sample is provided below.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(convenience\_means)}
\CommentTok{\#\textgreater{} [1] 4.8243}
\FunctionTok{sd}\NormalTok{(convenience\_means)}
\CommentTok{\#\textgreater{} [1] 0.8334471}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{8}
\tightlist
\item
  Compare the two distributions shown above. What is similar between the two distributions? What is different?
\end{enumerate}

\vspace{0.8in}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{9}
\item
  Using the plots above, explain why using a random number generator to generate a sample is a ``better'' method than choosing 10 words ``by eye'' (convenience sample).
  \vspace{0.8in}
\item
  Is random selection an unbiased method of selection? Explain your answer. Be sure to reference the created plots.
  \vspace{0.5in}
\end{enumerate}

Later in the semester we will learn about the Scope of Inference for a study. A diagram of Scope of Inference is show below:

\begin{center}\includegraphics[width=0.75\linewidth]{images/ScopeOfInferenceGreyscale} \end{center}

In this activity we have focused on sampling methods. Note that the sampling method used to select the sample determines the group of observation units the results of a study apply to. This is ``generalization.'' We will explore causation in Module 8.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{11}
\tightlist
\item
  What is the purpose of random selection of a sample from the population?
\end{enumerate}

\vspace{0.8in}

\subsection{Take-home messages}\label{take-home-messages-1}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  When we use a biased method of selection, we will over or underestimate the parameter, on average.
\item
  If the sampling method is biased, inferences made about the population based on a sample estimate will not be valid.
\item
  Random selection is an unbiased method of selection.
\item
  To determine if a sampling method is biased or unbiased, we compare the distribution of the estimates to the true value. We want our estimate to be on target or unbiased. When using unbiased methods of selection, the mean of the distribution matches or is very similar to our true parameter.
\item
  Random selection eliminates selection bias. However, random selection will not eliminate response or non-response bias.
\end{enumerate}

\subsection{Additional notes}\label{additional-notes-1}

For more practice on sampling methods, use the Module 1 Review worksheet in the Unit 1 Review Materials (pgs.108--109).

Use this space to summarize your thoughts and take additional notes on today's activity and material covered.

\newpage

\chapter{Probability}\label{probability}

\section{Vocabulary Review and Key Topics}\label{vocabulary-review-and-key-topics-1}

\subsection{Key topics}\label{key-topics-1}

Module 2 introduces the concept of probability as a long-run relative frequency and demonstrates how to use hypothetical two-way tables to set up a probability problem and solve for unconditional and conditional probabilities.

\subsection{Vocabulary}\label{vocabulary-1}

\begin{itemize}
\item
  \textbf{Probability} (of an event): the long-run proportion of times the event would occur if the random process were repeated indefinitely (under identical conditions).
\item
  \textbf{Conditional probability} (of an event \emph{given} another event): probability of an event calculated dependent on another event having occurred.
\item
  \textbf{Probability notation}:

  \begin{itemize}
  \item
    \(P(A)\): the probability of event \(A\).

    \begin{itemize}
    \tightlist
    \item
      This is the probability of a single event, \emph{unconditional} probability calculated out of the overall population.
    \end{itemize}
  \item
    \(P(A^C)\): the probability of the \textbf{complement} of event \(A\), or ``\(A\) complement''.

    \begin{itemize}
    \item
      This is the probability of the opposite of event \(A\), or ``not \(A\)''.
    \item
      \(P(A^C) = 1 - P(A)\)
    \end{itemize}
  \item
    \(P(A\text{ and }B)\): the probability of event \(A\) and \(B\).

    \begin{itemize}
    \tightlist
    \item
      The is the probability of an ``and'' event, \emph{unconditional} probability calculated out of the overall population.
    \end{itemize}
  \item
    \(P(A|B)\): the probability of event \(A\) given (conditional on) event \(B\).

    \begin{itemize}
    \tightlist
    \item
      This is a \emph{conditional} probability calculated out of the total population for which event \(B\) occurred.
    \end{itemize}
  \end{itemize}
\end{itemize}

\newpage

\section{Video Notes: Probability}\label{video-notes-probability}

Read Chapter 23 in the course textbook. Use the following videos to complete the video notes for Module 2.

\subsection{Course Videos}\label{course-videos-1}

\begin{itemize}
\tightlist
\item
  Probability
\end{itemize}

\setstretch{1}

\subsection*{Video: Probability (chapter 23)}\label{video-probability-chapter-23}
\addcontentsline{toc}{subsection}{Video: Probability (chapter 23)}

Example: Two variables were collected on a random sample of people who had ever been married; whether a person had ever smoked and whether a person had ever been divorced. The data are displayed in the following table. This survey was based on a random sample in the United States in the early 1990s, so the data should be representative of the adult population who had ever been married at that time.

\begin{itemize}
\item
  Let event D be a person has gone through a divorce
\item
  Let event S be a person smokes
\end{itemize}

\begin{center}
\begin{tabular}{|c|c|c|c|} \hline
\hspace{0.8in} & \hspace{0.35in} Has divorced \hspace{.35in} & \hspace{0.35in} Has never divorced  \hspace{0.35in} & \hspace{0.3in} Total \hspace{0.3in} \\ 
& & & \\ \hline
Smokes & 238 & 247 & 485 \\ 
& & & \\ \hline
Does not smoke & 374 & 810 & 1184 \\ 
& & & \\ \hline
Total & 612 & 1057 & 1669 \\ 
& & & \\ \hline
\end{tabular}
\end{center}
\vspace{.1in}

\begin{itemize}
\tightlist
\item
  What is the approximate probability that the person smoked?
\end{itemize}

\vspace{0.5in}

\begin{itemize}
\tightlist
\item
  What is the approximate probability that the person had ever been divorced?
\end{itemize}

\vspace{0.5in}

\begin{itemize}
\tightlist
\item
  Given that the person had been divorced, what is the probability that he or she smoked?
\end{itemize}

\vspace{0.5in}

\begin{itemize}
\tightlist
\item
  Given that the person smoked, what is the probability that he or she had been divorced?
\end{itemize}

\vspace{0.5in}

\setstretch{1.5}

\begin{itemize}
\item
  Random process: one in which the outcome is \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

  \begin{itemize}
  \tightlist
  \item
    Example: Rolling a fair die
  \end{itemize}
\item
  Event: something that could occur, something we want to find the probability of; Denoted using a capital letter.

  \begin{itemize}
  \tightlist
  \item
    Example: Getting a four when rolling a fair die
  \end{itemize}
\item
  Complement: opposite of the event; Denoted using a \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

  \begin{itemize}
  \tightlist
  \item
    Example: Getting any value but a four when rolling a fair die
  \end{itemize}
\item
  The probability of an event is the \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ of times the event would occur if the random process were repeated \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_; Denoted using \(P(event)\)

  \begin{itemize}
  \tightlist
  \item
    Example: the probability of getting a four when rolling a fair die is \_\_\_\_\_\_\_\_\_\_\_.
  \end{itemize}
\item
  Unconditional probability: calculated from the \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

  \begin{itemize}
  \item
    Unconditional probabilities do \textbf{not} depend any event occurring.
  \item
    The denominator of the probability will always be \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_.
  \item
    Two types of unconditional probabilities:

    \begin{itemize}
    \item
      The probability of a single event

      \begin{itemize}
      \tightlist
      \item
        Example from section 23.2: The probability of being late to class
      \end{itemize}
    \item
      An ``And'' probability

      \begin{itemize}
      \tightlist
      \item
        Example from section 23.2: The probability of finding an open parking spot in Lot 6 \textbf{and} being late to class
      \end{itemize}
    \end{itemize}
  \end{itemize}
\item
  Conditional probabilities: calculated \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ on the occurrence of another event.

  \begin{itemize}
  \item
    The denominator of the probability will be the total for the event \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ (or the event that is known to have occurred)
  \item
    Example from section 23.2: The probability of being late to class, \emph{given} that you parked in Lot 18
  \item
    Example from section 23.2: The probability of having parked in Lot 18, \emph{given} that you were late to class
  \end{itemize}
\end{itemize}

\textbf{Optional practice:} For each of the four probability questions about divorce and smoking status from the beginning of these vide notes, determine if the calculated probability was a conditional or unconditional probability and write it using proper notation.

\setstretch{1}

\subsubsection*{Creating a hypothetical two-way table}\label{creating-a-hypothetical-two-way-table}
\addcontentsline{toc}{subsubsection}{Creating a hypothetical two-way table}

Steps:

\begin{itemize}
\item
  Start with a large number like 100000.
\item
  Then use the unconditional probabilities to fill in the row or column totals.
\item
  Now use the conditional probabilities to begin filling in the interior cells.
\item
  Use subtraction to find the remaining interior cells.
\item
  Add the column values together for each row to find the row totals.
\item
  Add the row values together for each column to find the column totals.
\end{itemize}

Example: As a student at Montana State University, suppose your first class on Mondays is in Wilson Hall at 8:00am and you commute to school. You have a Bobcat parking permit. From past experience, you know that there is a 20\% chance of finding an open parking spot in Lot 6 by Animal Bioscience. Otherwise, you have to park in Lot 18 by graduate housing. If you find a spot in Lot 6, you only have a 5\% chance of being late to class. However, if you have to park in Lot 18, you have a 15\% chance of being late to class. What is the probability that you will be late to class this Monday?

\begin{itemize}
\tightlist
\item
  Let event A = finding an open parking spot in Lot 6 by Animal Bioscience
\item
  Let event C = being late to class
\end{itemize}

\setstretch{1.5}

Start by identifying the probability notation for each value given.

\begin{itemize}
\tightlist
\item
  0.20 =
\end{itemize}

\vspace{0.1in}

\begin{itemize}
\tightlist
\item
  0.05 =
\end{itemize}

\vspace{0.1in}

\begin{itemize}
\tightlist
\item
  0.15 =
\end{itemize}

\vspace{0.1in}

\begin{itemize}
\tightlist
\item
  Note for the table below, we will use 100,000 hypothetical Mondays (instead of 1,000 as shown in the textbook)
\end{itemize}

\setstretch{1}

\begin{center}
\begin{tabular}{|c|c|c|c|} \hline
\hspace{0.8in} & \hspace{0.35in} $C$ \hspace{.35in} & \hspace{0.35in} $C^C$  \hspace{0.35in} & \hspace{0.3in} Total \hspace{0.3in} \\ 
& & & \\ \hline
$A$& & & \\ 
& & & \\ \hline
$A^C$& & & \\ 
& & & \\ \hline
Total & & & 100,000 \\ 
& & & \\ \hline
\end{tabular}
\end{center}
\vspace{.1in}

For each of the following, determine if the probability is conditional or unconditional. Then write the probability in proper notation and calculate the value.

\begin{itemize}
\tightlist
\item
  What is the probability you are not late to class?
\end{itemize}

\vspace{1in}

\begin{itemize}
\tightlist
\item
  What is the probability that you park in Lot 6 and you are not late to class
\end{itemize}

\vspace{1in}

\begin{itemize}
\tightlist
\item
  Given that you were late to class, what is the probability you parked in Lot 18?
\end{itemize}

\vspace{1in}

\subsubsection*{Diagnostic tests}\label{diagnostic-tests}
\addcontentsline{toc}{subsubsection}{Diagnostic tests}

\begin{itemize}
\tightlist
\item
  Sensitivity:
\end{itemize}

\vspace{0.3in}

\begin{itemize}
\tightlist
\item
  Specificity:
\end{itemize}

\vspace{0.3in}

\begin{itemize}
\tightlist
\item
  Prevalence:
\end{itemize}

\vspace{0.3in}

\subsubsection*{Optional Notes: Additional Example}\label{optional-notes-additional-example-1}
\addcontentsline{toc}{subsubsection}{Optional Notes: Additional Example}

An airline has noticed that 30\% of passengers pre-pay for checked bags at the time the ticket is purchased. The no-show rate among customers that pre-pay for checked bags is 5\%, compared to 15\% among customers that do not pre-pay for checked bags.

\begin{itemize}
\tightlist
\item
  Let event B = customer pre-pays for checked bag
\item
  Let event N = customer no shows
\end{itemize}

\setstretch{1.5}

Start by identifying the probability notation for each value given.

\begin{itemize}
\tightlist
\item
  0.30 =
\end{itemize}

\vspace{0.1in}

\begin{itemize}
\tightlist
\item
  0.05 =
\end{itemize}

\vspace{0.1in}

\begin{itemize}
\tightlist
\item
  0.15 =
\end{itemize}

\vspace{0.1in}

\setstretch{1}

\begin{center}
\begin{tabular}{|c|c|c|c|} \hline
\hspace{0.8in} & \hspace{0.35in} $B$ \hspace{.35in} & \hspace{0.35in} $B^C$  \hspace{0.35in} & \hspace{0.3in} Total \hspace{0.3in} \\ 
& & & \\ \hline
$N$& & & \\ 
& & & \\ \hline
$N^C$& & & \\ 
& & & \\ \hline
Total & & & 100,000 \\ 
& & & \\ \hline
\end{tabular}
\end{center}
\vspace{.1in}

\begin{itemize}
\tightlist
\item
  What is the probability that a randomly selected customer who shows for the flight, pre-purchased checked bags?
\end{itemize}

\vspace{1in}

\subsection{Concept Check}\label{concept-check-1}

Be prepared for group discussion in the next class. One member from the table should write the answers to the following on the whiteboard.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  In the parking example, calculate and interpret the following: \(P(A^C|C^C)=\).
\end{enumerate}

\vspace{1in}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  What is the probability notation for 0.15 in the airline example?
\end{enumerate}

\vspace{1in}

\newpage

\section{Activity 3: Probability Studies}\label{activity-3-probability-studies}

\setstretch{1}

\subsection{Learning outcomes}\label{learning-outcomes-2}

\begin{itemize}
\item
  Recognize and simulate probabilities as long-run frequencies.
\item
  Construct two-way tables to evaluate conditional probabilities.
\end{itemize}

\subsection{Terminology review}\label{terminology-review-2}

In today's activity, we will cover two-way tables and probability. Some terms covered in this activity are:

\begin{itemize}
\item
  Proportions
\item
  Probability
\item
  Conditional probability
\item
  Two-way tables
\end{itemize}

To review these concepts, see Chapter 23 in the textbook.

\subsection*{Notes on probability}\label{notes-on-probability}
\addcontentsline{toc}{subsection}{Notes on probability}

The probability of an event is the long-run proportion of times the event would occur if the random process were repeated indefinitely (under identical conditions).

To calculate the probability of an event happening:

\[\text{probability} = \frac{\text{number of ways an event can happen}}{\text{total number of possible outcomes}}\]

For example, to calculate the probability of a coin flip landing on heads; there are only two outcomes (heads or tails) and only one possible way to land on heads.

\[P(heads) = \frac{1}{2} = 0.5\]

The figure below shows the long-run proportion of times a simulated coin flip lands on heads on the y-axis, and the number of tosses on the x-axis. Notice how the long-run proportion starts converging to 0.5 as the number of tosses increases.

\begin{figure}

{\centering \includegraphics[width=0.65\linewidth]{images/coinsim} 

}

\end{figure}

In today's activity we will discuss the probability of a single event, the probability of an ``and'' event, and the probability of a conditional event.

\subsubsection*{Probability notation}\label{probability-notation}
\addcontentsline{toc}{subsubsection}{Probability notation}

We will use the notation P(event) to represent the probability of an event and use letters to represent events. The following are notations for different probabilities where we are discussing event A and event B:

\begin{itemize}
\item
  \(P(A)\) represents the probability of event A
\item
  \(P(A^C)\) represents the probability of the complement of event A

  \begin{itemize}
  \tightlist
  \item
    Additionally, we can find the complement of event A by subtracting the probability of A from 1: \(P(A^C) = 1 - P(A)\)
  \end{itemize}
\item
  \(P(A \text{ and } B)\) represents the probability of events A and B
\item
  \(P(A|B)\) represents the probability of event A, given event B
\item
  \(P(B|A)\) represents the probability of event B, given event A
\end{itemize}

\subsubsection*{Probability questions}\label{probability-questions}
\addcontentsline{toc}{subsubsection}{Probability questions}

For the beginning of this activity we will start with discussing the probabilities associated with drawing a card from a standard card deck. In a card deck there are:

\begin{itemize}
\item
  52 cards
\item
  Half are red, half are black
\item
  Four suits: spades, hearts, diamonds, and clubs
\item
  Each suit has 13 cards: cards 2--10, ace, jack, queen, and king
\item
  Let A represent the event that a card is an ace
\item
  Let B represent the event that a card is red
\end{itemize}

To find the probability of selecting an ace, first start with determining how many aces are possible (four) and how many cards will we select from (total of 52).

\vspace{1in}

Find the probability of selecting a card that is not an ace. This is the complement of event A.

\vspace{1in}

Find the probability of selecting a red ace.

\vspace{1in}

Find the probability of selecting an ace given that the card is red.

\vspace{1in}

If a card drawn is an ace, what is the probability the card drawn is red.

\vspace{1in}

\subsection*{Calculating probabilities from a two-way table}\label{calculating-probabilities-from-a-two-way-table}
\addcontentsline{toc}{subsection}{Calculating probabilities from a two-way table}

Let's start with creating the two-way table. Your instructor will work through creating the table with the class.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  In 2014, the website FiveThirtyEight examined the works of Bob Ross to see what trends could be found. They determined that of all the paintings he created, 95\% of them contained at least one ``happy tree.'' Of those works with a happy tree, 43\% contained at least one ``almighty mountain.'' Of the paintings that did not have at least one happy tree, only 10\% contained at least one almighty mountain.
  \vspace{1mm}
\end{enumerate}

Let \(A\) = Bob Ross painting contains a happy tree, and \(B\) = Bob Ross painting contains an almighty mountain
\vspace{0.1in}

Create a hypothetical two-way table to represent the situation.

\begin{center}
\begin{tabular}{|c|c|c|c|} \hline
\hspace{0.8in} & \hspace{0.35in} $A$ \hspace{.35in} & \hspace{0.35in} $A^C$  \hspace{0.35in} & \hspace{0.3in} Total \hspace{0.3in} \\
& & & \\ \hline
$B$& & & \\
& & & \\ \hline
$B^C$& & & \\
& & & \\ \hline
Total & & & 100,000 \\
& & & \\ \hline
\end{tabular}
\end{center}
\vspace{.1in}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  What is the probability that a randomly selected Bob Ross painting contains both a ``happy tree'' and an ``almighty mountain''? Use appropriate probability notation.
\end{enumerate}

\vspace{0.5in}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  What is the probability that a selected Bob Ross painting without an ``almighty mountain'' contains a ``happy tree.'' Use appropriate probability notation.
\end{enumerate}

\vspace{0.5in}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  What is the probability that a selected Bob Ross painting does not contain a ``happy tree'' given it does not contain an ``almighty mountain''. Use appropriate probability notation.
\end{enumerate}

\vspace{0.55in}

\newpage

\newpage

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\item
  Since the early 1980s, the rapid antigen detection test (RADT) of group A \emph{streptococci} has been used to detect strep throat. A study of the accuracy of this test shows that the \textbf{sensitivity}, the probability of a positive RADT given the person has strep throat, is 86\% in children, while the \textbf{specificity}, the probability of a negative RADT given the person does not have strep throat, is 92\% in children. The \textbf{prevalence}, the probability of having group A strep, is 37\% in children. (Stewart et al. 2014)
  \vspace{1mm}

  Let \(A\) = the event the child has strep throat, and \(B\) = the event the child has a positive RADT.
  \vspace{0.1in}

  \begin{enumerate}
  \def\labelenumii{\alph{enumii}.}
  \item
    Identify what each numerical value given in the problem represents in probability notation.
    \vspace{.1in}

    0.86 =\\
    \vspace{.1in}

    0.92 =\\
    \vspace{.1in}

    0.37 =\\
    \vspace{.1in}
  \item
    Create a hypothetical two-way table to represent the situation.
  \end{enumerate}
\end{enumerate}

\begin{center}
\begin{tabular}{|c|c|c|c|} \hline
\hspace{0.8in} & \hspace{0.35in} $A$ \hspace{.35in} & \hspace{0.35in} $A^C$  \hspace{0.35in} & \hspace{0.3in} Total \hspace{0.3in} \\ 
& & & \\ \hline
$B$& & & \\ 
& & & \\ \hline
$B^C$& & & \\ 
& & & \\ \hline
Total & & & 100,000 \\ 
& & & \\ \hline
\end{tabular}
\end{center}
\vspace{.1in}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{2}
\item
  Find \(P(B)\). What does this probability represent in the context of the problem?
  \vspace{.8in}
\item
  Find the probability that a child with a positive RADT actually has strep throat. What is the notation used for this probability?
  \vspace{.8in}
\item
  What is the probability that a child does not have strep given that they have a positive RADT? What is the notation used for this probability?
\end{enumerate}

\vspace{0.8in}

\subsection{Take home messages}\label{take-home-messages-2}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Conditional probabilities are calculated dependent on a second variable. In probability notation, the variable following \texttt{\textbar{}} is the variable on which we are conditioning. The denominator used to calculate the probability will be the total for the variable on which we are conditioning.
\item
  When creating a two-way table we typically want to put the explanatory variable on the columns of the table and the response variable on the rows.
\item
  To fill in the two-way table, always start with the unconditional variable in the total row or column and then use the conditional probabilities to fill in the interior cells.
\end{enumerate}

\subsection{Additional notes}\label{additional-notes-2}

To understand probability you need lots of practice! Use the Module 2 Review in the Unit 1 Review Material (pgs. 110--111) for more practice problems.

Use this space to summarize your thoughts and take additional notes on today's activity and material covered.

\newpage

\chapter{Exploring Categorical Data: Exploratory Data Analysis and Inference using Simulation-based Methods}\label{exploring-categorical-data-exploratory-data-analysis-and-inference-using-simulation-based-methods}

\section{Vocabulary Review and Key Topics}\label{vocabulary-review-and-key-topics-2}

Review the Golden Ticket posted in the resources at the end of the coursepack for a summary of a single categorical variable.

\subsection{Key topics}\label{key-topics-2}

Module 3 introduces the steps of the statistical investigation process. We will conduct \textbf{exploratory data analysis} (summary statistics and plots) and simulation-based \textbf{inference} (hypothesis testing and confidence intervals) in the single categorical variable (one proportion) scenario.

\begin{itemize}
\item
  Notation for a sample proportion: \(\hat{p}\)
\item
  Notation for a population proportion: \(\pi\)
\item
  Types of plots for a single categorical variable:

  \begin{itemize}
  \item
    Frequency bar plot
  \item
    Relative frequency bar plot
  \end{itemize}
\end{itemize}

Exploratory data analysis is step 3 of the statistical investigation process. We will then use simulation-based methods \textbf{to find evidence of an effect by finding a p-value} and \textbf{estimating how large the effect is by creating a confidence interval} in the one proportion (one categorical variable) scenario. These are steps 4 and 5 from the steps of the statistical investigation process.

\subsubsection*{Steps of the statistical investigation process}\label{steps-of-the-statistical-investigation-process}
\addcontentsline{toc}{subsubsection}{Steps of the statistical investigation process}

As we move through the semester we will work through the six steps of the statistical investigation process.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Ask a research question.
\item
  Design a study and collect data.
\item
  Summarize and visualize the data.
\item
  Use statistical analysis methods to draw inferences from the data.
\item
  Communicate the results and answer the research question.
\item
  Revisit and look forward.
\end{enumerate}

\subsection{Vocabulary}\label{vocabulary-2}

\begin{itemize}
\item
  \textbf{Summary measure}: a numerical quantity that summarizes data. Summary measures covered in STAT 216 include: single proportion, difference in proportions, single mean, paired mean difference, difference in means, correlation, and slope of a regression line.

  \begin{itemize}
  \tightlist
  \item
    For a single categorical variable, a proportion is calculated.
  \end{itemize}
\item
  \textbf{Summary statistic (point estimate)}: the value of a numerical summary measure computed from \emph{sample} data.

  \begin{itemize}
  \item
    To interpret in context include:

    \begin{itemize}
    \item
      Summary measure (in context)
    \item
      Value of the statistic
    \end{itemize}
  \end{itemize}
\item
  \textbf{Parameter of interest}: a numerical summary measure of the entire \emph{population} in which we are interested.

  \begin{itemize}
  \item
    The value of the parameter of interest is unknown (unless we have access to the entire population).
  \item
    To write in context:

    \begin{itemize}
    \item
      Population word (true, long-run, population)
    \item
      Summary measure (depends on the type of data)
    \item
      Context

      \begin{itemize}
      \item
        Observational units
      \item
        Variable(s)
      \end{itemize}
    \end{itemize}
  \end{itemize}
\item
  For a single categorical variable, the category that we are counting the proportion of is generically called a ``\textbf{success}'', with categories not a success labeled ``\textbf{failure}''. Thus, a sample proportion is the ``proportion of successes'' in the sample: the total number of successes divided by the sample size (\(n\)).
\end{itemize}

\subsubsection*{Plotting one categorical variable}\label{plotting-one-categorical-variable}
\addcontentsline{toc}{subsubsection}{Plotting one categorical variable}

\begin{itemize}
\item
  \textbf{Frequency bar plot}: plots the count (frequency) of observational units in each level of a categorical variable. R code to create a frequency bar plot:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{object }\SpecialCharTok{\%\textgreater{}\%} \CommentTok{\# Data set piped into...}
\FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ variable)) }\SpecialCharTok{+}   \CommentTok{\# This specifies the variable}
\FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{stat =} \StringTok{"count"}\NormalTok{) }\SpecialCharTok{+}  \CommentTok{\# Tell it to make a bar plot}
\FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Don\textquotesingle{}t forget to title your plot!"}\NormalTok{,  }
   \CommentTok{\# Give your plot a title}
   \AttributeTok{x =} \StringTok{"x{-}axis label"}\NormalTok{,   }\CommentTok{\# Label the x axis}
   \AttributeTok{y =} \StringTok{"Frequency"}\NormalTok{)  }\CommentTok{\# Label the y axis}
\end{Highlighting}
\end{Shaded}
\item
  \textbf{Relative frequency bar plot}: plots the proportion (relative frequency) of observational units in each level of a categorical variable. R code to create a relative frequency bar plot:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{object }\SpecialCharTok{\%\textgreater{}\%} \CommentTok{\# Data set piped into...}
\FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ variable)) }\SpecialCharTok{+}   \CommentTok{\# This specifies the variable}
\FunctionTok{geom\_bar}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =} \FunctionTok{after\_stat}\NormalTok{(prop), }\AttributeTok{group =} \DecValTok{1}\NormalTok{)) }\SpecialCharTok{+}  \CommentTok{\# Tell it to make a bar plot with proportions}
\FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Don\textquotesingle{}t forget to title your plot!"}\NormalTok{,  }
   \CommentTok{\# Give your plot a title}
   \AttributeTok{x =} \StringTok{"x{-}axis label"}\NormalTok{,   }\CommentTok{\# Label the x axis}
   \AttributeTok{y =} \StringTok{"Relative Frequency"}\NormalTok{)  }\CommentTok{\# Label the y axis}
\end{Highlighting}
\end{Shaded}
\end{itemize}

\subsubsection*{Inference}\label{inference}
\addcontentsline{toc}{subsubsection}{Inference}

\begin{itemize}
\item
  \textbf{Sampling distribution} (of a statistic): the distribution of possible values of a statistic across repeated samples of the same size and under the same conditions.

  \begin{itemize}
  \tightlist
  \item
    We can create a \emph{simulated} sampling distribution using simulation-based methods to simulate many samples, or we can mathematically model the sampling distribution (theory-based methods).
  \end{itemize}
\item
  \textbf{Hypothesis testing}: a formal statistical technique for evaluating two competing possibilities about a population: the null hypothesis and alternative hypothesis.

  \begin{itemize}
  \item
    When we observe an effect in a sample, we would like to determine if this observed effect represents an actual effect in the population, or whether it was simply due to random chance.
  \item
    A hypothesis test helps us answer the following question about the population: How strong is the \emph{evidence} of an effect?
  \end{itemize}
\item
  \textbf{Null hypothesis}: typically represents a statement of ``no difference'', ``no effect'', or the status quo.

  \begin{itemize}
  \tightlist
  \item
    The null hypothesis is what we assume is true when calculating the p-value. Thus, we can never have evidence \emph{for} the null hypothesis---we cannot ``accept'' a null hypothesis---we can only find evidence \emph{against} the null hypothesis if the observed data is very unlikely to have occurred under the assumption that the null hypothesis is true.
  \end{itemize}
\item
  \textbf{Alternative hypothesis}: represents an alternative claim under consideration and is often represented by a range of possible values for the parameter of interest.

  \begin{itemize}
  \tightlist
  \item
    The alternative hypothesis is determined by the research question.
  \end{itemize}
\item
  \textbf{Hypotheses in notation for a single proportion}: In the hypotheses below, \(\pi_0\) is the \textbf{null value}.
\end{itemize}

\[H_0: \pi = \pi_0\]
\[H_A: \pi \left\{
\begin{array}{ll}
< \\
\ne \\
< \\
\end{array}
\right\}
\pi_0 \]

\begin{itemize}
\item
  \textbf{P-value}: the probability of the value of the observed sample statistic or a value more extreme, if the null hypothesis were true.

  \begin{itemize}
  \item
    To write in context include:

    \begin{itemize}
    \item
      Statement about probability or proportion of samples
    \item
      Statistic (summary measure and value)
    \item
      Direction of the alternative
    \item
      Null hypothesis (in context)
    \end{itemize}
  \end{itemize}
\item
  \textbf{Strength of evidence}: the p-value indicates the amount of evidence there is against the null hypothesis. The smaller the p-value the more evidence there is against the null hypothesis.
\end{itemize}

\begin{center}\includegraphics[width=0.9\linewidth]{images/soe_gradient_gray} \end{center}

\newpage

\begin{itemize}
\item
  \textbf{Conclusion} (to a hypothesis test): answers the research question. How much evidence is there in support of the alternative hypothesis?

  \begin{itemize}
  \item
    To write in context include:

    \begin{itemize}
    \item
      Amount of evidence
    \item
      Parameter of interest
    \item
      Direction of the alternative hypothesis
    \end{itemize}
  \end{itemize}
\item
  \textbf{Confidence interval}: an interval estimate for the parameter of interest; an interval of \emph{plausible values} for the parameter.

  \begin{itemize}
  \item
    A confidence interval helps us answer the following question about the population: How \emph{large} is the effect?
  \item
    To write in context include:

    \begin{itemize}
    \item
      How confident you are (e.g., 90\%, 95\%, 98\%, 99\%)
    \item
      Parameter of interest
    \item
      Calculated interval
    \end{itemize}
  \end{itemize}
\end{itemize}

\subsubsection*{Simulation-based inference for a single proportion}\label{simulation-based-inference-for-a-single-proportion}
\addcontentsline{toc}{subsubsection}{Simulation-based inference for a single proportion}

\begin{itemize}
\item
  \textbf{Conditions necessary to use simulation-based methods for inference for a single categorical variable}:

  \begin{itemize}
  \tightlist
  \item
    \textbf{Independence}: observational units must be independent of one another; the outcome of one observational unit should have no influence on the outcome of another.
  \end{itemize}
\item
  \textbf{Null distribution}: a sampling distribution of simulated sample statistics created under the assumption that the null hypothesis is true
\item
  \textbf{Simulation-based methods to create the null distribution}: a process of using a computer program (e.g., R) to simulate many samples that we would expect based on the null hypothesis.

  R code to use simulation methods for one categorical variable to find the p-value, \texttt{one\_proportion\_test} (from the \texttt{catstats} package), is shown below.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{one\_proportion\_test}\NormalTok{(}\AttributeTok{probability\_success =}\NormalTok{ xx, }\CommentTok{\# Null hypothesis value}
      \AttributeTok{sample\_size =}\NormalTok{ xx, }\CommentTok{\# Enter sample size}
      \AttributeTok{number\_repetitions =} \DecValTok{10000}\NormalTok{, }\CommentTok{\# Enter number of simulations}
      \AttributeTok{as\_extreme\_as =}\NormalTok{ xx, }\CommentTok{\# Observed statistic}
      \AttributeTok{direction =} \StringTok{"xx"}\NormalTok{, }\CommentTok{\# Specify direction of alternative hypothesis}
      \AttributeTok{summary\_measure =} \StringTok{"proportion"}\NormalTok{) }\CommentTok{\# Reporting proportion or number of successes?}
\end{Highlighting}
\end{Shaded}
\item
  \textbf{Bootstrapping}: creating a simulated sample of the same size as the original sample by sampling with replacement from the original sample.
\item
  \textbf{Simulation-based methods to create the bootstrap distribution}: a process of using a computer program to simulate many bootstrapped samples.

  R code to use simulation methods for one categorical variable to find a confidence interval, \texttt{one\_proportion\_bootstrap\_CI} (from the \texttt{catstats} package), is shown below.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{one\_proportion\_bootstrap\_CI}\NormalTok{(}\AttributeTok{sample\_size =}\NormalTok{ xx, }\CommentTok{\# Sample size}
                \AttributeTok{number\_successes =}\NormalTok{ xx, }\CommentTok{\# Observed number of successes}
                \AttributeTok{number\_repetitions =} \DecValTok{10000}\NormalTok{, }\CommentTok{\# Number of bootstrap samples to use}
                \AttributeTok{confidence\_level =} \FloatTok{0.95}\NormalTok{) }\CommentTok{\# Confidence level as a decimal}
\end{Highlighting}
\end{Shaded}
\item
  \textbf{Percentile method}: process to find the confidence interval from the bootstrap distribution.

  \begin{itemize}
  \item
    A 90\% confidence interval will be found between the 5th and 95th percentiles of the bootstrap distribution.
  \item
    A 95\% confidence interval will be found between the 2.5th and 97.5th percentiles of the bootstrap distribution.
  \item
    A 99\% confidence interval will be found between the 0.5th and 99.5th percentiles of the bootstrap distribution.
  \end{itemize}
\end{itemize}

\newpage

\section{Video Notes: Analysis of One Categorical Variable}\label{video-notes-analysis-of-one-categorical-variable}

Read Chapter 3, 4, 9, 10 and Sections 14.1 and 14.2 in the course textbook. Use the following videos to complete the video notes for Module 3.

\subsection{Course Videos}\label{course-videos-2}

\begin{itemize}
\item
  One\_Categorical\_Variable\_EDA
\item
  Hypothesis\_Testing
\item
  Simulation\_Tests\_One\_Categorical\_Variable
\item
  Confidence\_Intervals
\item
  Bootstrap\_Intervals\_One\_Categorical\_Variable
\end{itemize}

\setstretch{1}

\subsection*{Video: One Categorical Variable EDA (sections 4.1 and 4.2 - summarizing and displaying one categorical variable)}\label{video-one-categorical-variable-eda-sections-4.1-and-4.2---summarizing-and-displaying-one-categorical-variable}
\addcontentsline{toc}{subsection}{Video: One Categorical Variable EDA (sections 4.1 and 4.2 - summarizing and displaying one categorical variable)}

\begin{itemize}
\item
  A \_\_\_\_\_\_\_\_\_\_\_\_\_\_ is calculated on data from a sample
\item
  The \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ is calculated on data from a population; it is typically unknown and therefore we will define it \emph{in words}
\item
  The parameter should include:

  \begin{itemize}
  \item
    Population word (true, long-run, population)
  \item
    Summary measure (depends on the type of data)
  \item
    Context

    \begin{itemize}
    \item
      Observational units
    \item
      Variable(s)
    \end{itemize}
  \end{itemize}
\end{itemize}

Categorical data can be numerically summarized by calculating a \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ from the data set.

Notation used for the population proportion:

\vspace{0.2in}

Notation used for the sample proportion:

\vspace{0.2in}

\setstretch{1.5}

Categorical data can be summarized in a \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ table, which reports counts or a \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ table, which reports proportions.

\setstretch{1}

Types of plots for a single categorical variable:

\vspace{0.4in}

\vspace{2mm}

Example from section 4.1 using the \texttt{email} data set:

\begin{itemize}
\tightlist
\item
  Identify the observational units.
\end{itemize}

\vspace{0.2in}

\begin{itemize}
\tightlist
\item
  What type of variable is \texttt{number}?
\end{itemize}

\vspace{0.2in}

\begin{itemize}
\tightlist
\item
  Is Table 4.3 a frequency or relative frequency table?
\end{itemize}

\vspace{0.2in}

\begin{itemize}
\tightlist
\item
  What proportion of emails had no number in them? Is this value a statistic or a parameter? Write it using proper notation.
\end{itemize}

\vspace{0.3in}

\setstretch{1.5}

\begin{itemize}
\tightlist
\item
  Compare the two plots (frequency bar plot and relative frequency bar plot) of the variable \texttt{number} in Figure 4.1 in section 4.2 of the text. Note that the x-axis is the \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ in the two plots. However, the \_\_\_\_\_\_\_\_\_\_\_\_\_\_ differs. The scale for the frequency bar plot goes from \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ and the scale for the relative frequency bar plot is from \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_.
\end{itemize}

\subsubsection*{Optional Notes: Additional Example}\label{optional-notes-additional-example-2}
\addcontentsline{toc}{subsubsection}{Optional Notes: Additional Example}

Gallatin Valley is the fastest growing county in Montana. You'll often hear Bozeman residents complaining about the `out-of-staters' moving in. A local real estate agent recorded data on a random sample of 100 home sales over the last year at her company and noted where the buyers were moving from as well as the age of the person or average age of a couple buying a home. The variable age was binned into two categories, ``Under30'' and ``Over30.'' Additionally, the variable, state the buyers were moving from, was created as a binary variable, ``Out'' for a location out of state and ``In'' for a location in state.

The following code reads in the data set, \texttt{moving\_to\_mt} and names the object moving.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{moving }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"data/moving\_to\_mt.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

The \texttt{R} function \texttt{glimpse} was used to give the following output.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{glimpse}\NormalTok{(moving)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
#> Rows: 100
#> Columns: 4
#> $ From      <chr> "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", ~
#> $ Age_Group <chr> "Under30", "Under30", "Under30", "Under30", "Under30", "Unde~
#> $ Age       <int> 25, 26, 27, 27, 29, 29, 35, 37, 49, 63, 65, 77, 22, 24, 24, ~
#> $ InOut     <chr> "Out", "Out", "Out", "Out", "Out", "Out", "Out", "Out", "Out~
\end{verbatim}

\begin{itemize}
\tightlist
\item
  What are the observational units in this study?
\end{itemize}

\vspace{0.3in}

\begin{itemize}
\tightlist
\item
  What type of variable is \texttt{Age}?
\end{itemize}

\vspace{0.3in}

\begin{itemize}
\tightlist
\item
  What type of variable is \texttt{Age\_Group}?
\end{itemize}

To further analyze the categorical variable, \texttt{From}, we can create either a frequency table:

\begin{verbatim}
#>   From  n
#> 1   CA 12
#> 2   CO  8
#> 3   MT 61
#> 4   WA 19
\end{verbatim}

Or a relative frequency table:

\begin{verbatim}
#>   From  n freq
#> 1   CA 12 0.12
#> 2   CO  8 0.08
#> 3   MT 61 0.61
#> 4   WA 19 0.19
\end{verbatim}

\begin{itemize}
\tightlist
\item
  How many home sales have buyers from WA?
\end{itemize}

\vspace{0.2in}

\begin{itemize}
\tightlist
\item
  What proportion of sampled home sales have buyers from WA?
\end{itemize}

\vspace{0.2in}

\begin{itemize}
\tightlist
\item
  What notation is used for the proportion of home sale buyers that that are from WA?
\end{itemize}

\vspace{0.2in}

The following code in \texttt{R} will create a frequency bar plot of the variable, \texttt{From}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{moving }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ From))}\SpecialCharTok{+} \CommentTok{\#Enter the variable to plot}
    \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{stat =} \StringTok{"count"}\NormalTok{) }\SpecialCharTok{+} 
    \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Frequency Bar Plot of State of Origin for}
\StringTok{         Gallatin County Home Sales"}\NormalTok{, }
         \CommentTok{\#Title your plot (type of plot, observational units, variable)}
       \AttributeTok{y =} \StringTok{"Frequency"}\NormalTok{, }\CommentTok{\#y{-}axis label}
       \AttributeTok{x =} \StringTok{"State of Origin"}\NormalTok{) }\CommentTok{\#x{-}axis label}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=0.65\linewidth]{03-VN03-EDA_OneCatSimulation_files/figure-latex/unnamed-chunk-5-1} \end{center}

\begin{itemize}
\tightlist
\item
  What can we see from this plot?
\end{itemize}

\vspace{0.3in}

Additionally, we can create a relative frequency bar plot.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{moving }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ From))}\SpecialCharTok{+} \CommentTok{\#Enter the variable to plot}
  \FunctionTok{geom\_bar}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =} \FunctionTok{after\_stat}\NormalTok{(prop), }\AttributeTok{group =} \DecValTok{1}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Relative Frequency Bar Plot of State of Origin }
\StringTok{       for Gallatin County Home Sales"}\NormalTok{, }
       \CommentTok{\#Title your plot}
       \AttributeTok{y =} \StringTok{"Relative Frequency"}\NormalTok{, }\CommentTok{\#y{-}axis label}
       \AttributeTok{x =} \StringTok{"State of Origin"}\NormalTok{) }\CommentTok{\#x{-}axis label}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=0.65\linewidth]{03-VN03-EDA_OneCatSimulation_files/figure-latex/unnamed-chunk-6-1} \end{center}

\setstretch{1}

\subsection*{Video: Hypothesis Testing (chapter 9)}\label{video-hypothesis-testing-chapter-9}
\addcontentsline{toc}{subsection}{Video: Hypothesis Testing (chapter 9)}

Purpose of a hypothesis test:

\begin{itemize}
\item
  Use data collected on a sample to give information about the population.
\item
  Determines \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ of \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ of an effect
\end{itemize}

General steps of a hypothesis test

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Write a research question and hypotheses.
\item
  Collect data and calculate a summary statistic.
\item
  Model a sampling distribution which assumes the null hypothesis is true.
\item
  Calculate a p-value.
\item
  Draw conclusions based on a p-value.
\end{enumerate}

\subsection*{Hypotheses}\label{hypotheses}
\addcontentsline{toc}{subsection}{Hypotheses}

\setstretch{1.5}

\begin{itemize}
\item
  Always hypothesize about the \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_, so will always be written in terms of \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_.
\item
  Both null and alternative hypotheses will compare the parameter to the same value, only the \emph{sign} will change.
\end{itemize}

\setstretch{1}

\subsubsection*{Null hypothesis}\label{null-hypothesis}
\addcontentsline{toc}{subsubsection}{Null hypothesis}

\begin{itemize}
\item
  Skeptical perspective, no difference, no effect, random chance
\item
  What the researcher hopes is \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_.
\item
  Will always use the \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ sign.
\end{itemize}

Notation:

\vspace{0.2in}

\subsubsection*{Alternative hypothesis}\label{alternative-hypothesis}
\addcontentsline{toc}{subsubsection}{Alternative hypothesis}

\begin{itemize}
\item
  New perspective, a chance, a difference, an effect
\item
  What the researcher hopes is \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_.
\item
  The sign of the alternative hypothesis reflects the \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_.
\end{itemize}

Notation \emph{(write all three options)}:

\vspace{0.6in}

\subsection*{Simulation vs.~Theory-based Methods}\label{simulation-vs.-theory-based-methods}
\addcontentsline{toc}{subsection}{Simulation vs.~Theory-based Methods}

\subsubsection*{Simulation-based method}\label{simulation-based-method}
\addcontentsline{toc}{subsubsection}{Simulation-based method}

\setstretch{1.5}

Creation of the null distribution

\begin{itemize}
\tightlist
\item
  Simulate many samples assuming
\end{itemize}

\vspace{0.2in}

\begin{itemize}
\item
  Find the proportion of \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ at least as extreme as the observed sample \_\_\_\_\_\_\_\_\_\_\_\_
\item
  The null distribution estimates the sample to sample variability expected in the population
\end{itemize}

\setstretch{1}

\subsubsection*{Theory-based method}\label{theory-based-method}
\addcontentsline{toc}{subsubsection}{Theory-based method}

\begin{itemize}
\item
  Use a mathematical model to determine a distribution under the null hypothesis
\item
  Compare the observed sample statistic to the model to calculate a probability
\item
  \emph{Theory-based methods will be discussed in the next module}
\end{itemize}

\subsubsection*{P-value}\label{p-value}
\addcontentsline{toc}{subsubsection}{P-value}

\setstretch{1.5}

\begin{itemize}
\item
  What does the p-value measure?

  \begin{itemize}
  \tightlist
  \item
    Probability of observing the sample \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ or more \_\_\_\_\_\_\_\_\_\_
    assuming the \_\_\_\_\_\_\_\_ hypothesis is \_\_\_\_\_\_\_\_\_\_.
  \end{itemize}
\item
  How much evidence does the p-value provide against the null hypothesis?
\end{itemize}

\begin{center}\includegraphics[width=0.75\linewidth]{images/soe_gradient_gray} \end{center}

\rgi \rgi - The \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ the p-value, the \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ the evidence against the null hypothesis.

\begin{itemize}
\tightlist
\item
  Write a conclusion based on the p-value.
\end{itemize}

\rgi \rgi - Answers the \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ question.

\rgi \rgi - Amount of \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ in support of the \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ hypothesis.

\begin{itemize}
\tightlist
\item
  Decision: can we reject or fail to reject the null hypothesis?
\end{itemize}

\rgi - Significance level: cut-off of ``small'' vs ``large'' p-value

\rgi \rgi - \(\text{p-value} \le \alpha\)

\rgi \rgi \rgi - Strong enough evidence against the null hypothesis

\rgi \rgi \rgi - Decision:

\vspace{0.2in}

\rgi \rgi \rgi - Results are \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ significant.

\rgi \rgi - \(\text{p-value} > \alpha\)

\rgi \rgi \rgi - Not enough evidence against the null hypothesis

\rgi \rgi \rgi - Decision:

\vspace{0.17in}

\rgi \rgi \rgi - Results are not \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ significant.

\setstretch{1}

\subsection*{Hypothesis Testing/Justice System}\label{hypothesis-testingjustice-system}
\addcontentsline{toc}{subsection}{Hypothesis Testing/Justice System}

\setstretch{1.5}

\begin{itemize}
\item
  Null hypothesis: The defendant is \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
\item
  Alternative hypothesis: The defendant is \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
\item
  Prosecution collects evidence (data) and presents that evidence to a jury
\item
  Two possible outcomes:

  \begin{itemize}
  \item
    Strong evidence against \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ -\textgreater{} jury finds the defendant \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
  \item
    Not enough evidence against \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ -\textgreater{} jury finds the defendant \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
  \end{itemize}
\end{itemize}

\subsubsection*{Example: Martian Alphabet}\label{example-martian-alphabet}
\addcontentsline{toc}{subsubsection}{Example: Martian Alphabet}

Review the Martian Alphabet example from sections 9.1 and 9.3.2

\begin{itemize}
\item
  Write the null hypothesis in words and in notation:

  \rgi \rgi In words: \(H_0:\)
\end{itemize}

\vspace{0.4in}

\rgi \rgi In notation: \(H_0:\pi=\) \_\_\_\_\_, where \(\pi\) represents the \_\_\_\_\_\_\_\_\_\_\_ proportion of humans that would \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_.

\begin{itemize}
\item
  Write the alternative hypothesis in words and in notation:

  \rgi \rgi In words: \(H_A:\)
\end{itemize}

\vspace{0.4in}

\rgi \rgi In notation: \(H_A:\pi\) \_\_\_\_\_\_\_\_\_ (a \_\_\_\_\_\_\_\_ sign represents the research question - that humans have a \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ for choosing Bumba on the left)

\begin{itemize}
\tightlist
\item
  What is the value of the statistic? Write it using proper notation.
\end{itemize}

\vspace{0.2in}

\begin{itemize}
\tightlist
\item
  Review Figure 9.2. Why is the plot centered around 0.5? What does each ``dot'' on the plot represent?
\end{itemize}

\vspace{0.4in}

\begin{itemize}
\tightlist
\item
  Does the statistic seem likely or unlikely to occur if humans are picking a shape randomly? What about Figure 9.2 helps us to answer this question?
\end{itemize}

\vspace{0.4in}

\setstretch{1.5}

\begin{itemize}
\tightlist
\item
  The p-value of the test is \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_. This p-value provides \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ evidence against the \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ hypothesis and for the \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ hypothesis. The results from this study \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ be considered statistically significant.
\end{itemize}

\vspace{0.1in}

\subsection*{Video: Simulation Tests for One Categorical Variable (section 14.1)}\label{video-simulation-tests-for-one-categorical-variable-section-14.1}
\addcontentsline{toc}{subsection}{Video: Simulation Tests for One Categorical Variable (section 14.1)}

Review the Medical Consultant example from section 14.1.

Identify the observational units.

\vspace{0.3in}

Identify the variable collected.

\vspace{0.3in}

Is the variable categorical or quantitative? If categorical, define a ``success''; if quantitative, state the units of measure.

\vspace{0.3in}

Define the parameter in words and write it using proper notation

\vspace{0.5in}

Write the null and alternative hypotheses in words and in proper notation:

\rgi In words:

\rgi \rgi \(H_0:\)

\vspace{0.45in}

\rgi \rgi \(H_A:\)

\vspace{0.45in}

\newpage

\rgi In notation:

\vspace{1mm}

\rgi \rgi \(H_0:\)

\vspace{0.2in}

\rgi \rgi \(H_A:\)

\vspace{0.2in}

Calculate the value of the statistic and write it using proper notation:

\vspace{0.2in}

\subsubsection*{Simulation-based method}\label{simulation-based-method-1}
\addcontentsline{toc}{subsubsection}{Simulation-based method}

\begin{itemize}
\item
  Simulate many samples assuming \(H_0: \pi = \pi_0\)

  \begin{itemize}
  \item
    Create a spinner with that represents the null value
  \item
    Spin the spinner \(n\) times
  \item
    Calculate and plot the simulated sample proportion from each simulation
  \item
    Repeat 10000 times (simulations) to create the null distribution
  \item
    Find the proportion of simulations at least as extreme as \(\hat{p}\)
  \end{itemize}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{216}\NormalTok{)}
\FunctionTok{one\_proportion\_test}\NormalTok{(}\AttributeTok{probability\_success =} \FloatTok{0.10}\NormalTok{, }\CommentTok{\# Null hypothesis value}
          \AttributeTok{sample\_size =} \DecValTok{62}\NormalTok{, }\CommentTok{\# Enter sample size}
          \AttributeTok{number\_repetitions =} \DecValTok{10000}\NormalTok{, }\CommentTok{\# Enter number of simulations}
          \AttributeTok{as\_extreme\_as =} \FloatTok{0.0484}\NormalTok{, }\CommentTok{\# Observed statistic}
          \AttributeTok{direction =} \StringTok{"less"}\NormalTok{, }\CommentTok{\# Specify direction of alternative hypothesis}
          \AttributeTok{summary\_measure =} \StringTok{"proportion"}\NormalTok{) }\CommentTok{\# Reporting proportion or number of successes?}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=0.65\linewidth]{03-VN03-EDA_OneCatSimulation_files/figure-latex/unnamed-chunk-8-1} \end{center}

Explain why the null distribution is centered at the value of approximately 0.10:

\vspace{0.5in}

Where is the red line plotted on the null distribution? Why is that value important?

\vspace{0.3in}

Why is the area left of the red line shaded on the null distribution?

\vspace{0.3in}

Interpretation of the p-value:

\begin{itemize}
\item
  Statement about probability or proportion of samples
\item
  Statistic (summary measure and value) and Direction of the alternative
\item
  Null hypothesis (population reference, summary measure, equal to null value)
\item
  Context of the problem (observational units, variable(s))
\end{itemize}

Two example p-value interpretations are provided below. Identify each of the components within the two examples:

\begin{itemize}
\item
  Example 1: There is a 12.36\% probability of observing three (3) or fewer complications out of sixty-two (63) liver donor surgeries in the US, if the true proportion of complications is 0.10.
\item
  Example 2: If 10\% of all liver donor surgeries in the US result in a complication, 1236/10000 samples would simulate a proportion of complications of 0.048 or less.
\end{itemize}

\vspace{0.1in}

Conclusion:

\begin{itemize}
\item
  Amount of evidence
\item
  For the alternative hypothesis (population reference, summary measure, direction, null value)
\item
  Context (observational units, variable(s))
\end{itemize}

An example conclusion is provided below. Identify each of the components within the example:

\begin{itemize}
\tightlist
\item
  There is little to no that the proportion of all liver donor surgeries in the US that result in a complication is less than 0.10.
\end{itemize}

\vspace{0.1in}

Generalization:

\begin{itemize}
\tightlist
\item
  Can the results of the study be generalized to the target population?
\end{itemize}

\vspace{0.4in}

\newpage

\subsection*{Video: Confidence intervals (chapter 10)}\label{video-confidence-intervals-chapter-10}
\addcontentsline{toc}{subsection}{Video: Confidence intervals (chapter 10)}

\rgi \(\text{statistic} \pm \text{margin of error}\)

Vocabulary:

\begin{itemize}
\tightlist
\item
  Point estimate:
\end{itemize}

\vspace{0.3in}

\begin{itemize}
\tightlist
\item
  Margin of error:
\end{itemize}

\vspace{0.3in}

\setstretch{1.5}

Purpose of a confidence interval

\begin{itemize}
\item
  To give an \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ for the parameter of interest
\item
  Determines how \_\_\_\_\_\_\_\_\_\_\_\_\_\_ an effect is
\end{itemize}

\setstretch{1}

\subsubsection*{Sampling distribution}\label{sampling-distribution}
\addcontentsline{toc}{subsubsection}{Sampling distribution}

\setstretch{1.5}

\begin{itemize}
\item
  Ideally, we would take many samples of the same \_\_\_\_\_\_\_\_\_\_\_ from the same population to create a sampling distribution
\item
  But only have 1 sample, so we will \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ with \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ from the one sample.
\item
  Need to estimate the sampling distribution to see the \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ in the sample
\end{itemize}

\setstretch{1}

\subsubsection*{Simulation-based methods}\label{simulation-based-methods}
\addcontentsline{toc}{subsubsection}{Simulation-based methods}

Bootstrap distribution:

\begin{itemize}
\item
  Write the response variable values on cards
\item
  Sample with replacement \(n\) times (bootstrapping)
\item
  Calculate and plot the simulated difference in sample means from each simulation
\item
  Repeat 10000 times (simulations) to create the bootstrap distribution
\item
  Find the cut-offs for the middle X\% (confidence level) in a bootstrap distribution.
\end{itemize}

What is bootstrapping?

\begin{itemize}
\item
  Assume the ``population'' is many, many copies of the original sample.
\item
  Randomly sample with replacement from the original sample \(n\) times.
\end{itemize}

\subsubsection*{Example: Medical Consultant}\label{example-medical-consultant}
\addcontentsline{toc}{subsubsection}{Example: Medical Consultant}

Review the Medical Consultant example in section 10.1.

\begin{itemize}
\tightlist
\item
  Is 0.048 the statistic or the parameter? How do you know?
\end{itemize}

\vspace{0.4in}

\begin{itemize}
\item
  Review Figure 10.6 in section 10.1.2.

  \begin{itemize}
  \tightlist
  \item
    Why is the plot centered near 0.048? What does each ``dot'' on the plot represent?
  \end{itemize}

  \vspace{0.4in}

  \begin{itemize}
  \tightlist
  \item
    Why are the 2.5th and 97.5th percentiles of the bootstrap distribution marked? What are the values of these two percentiles?
  \end{itemize}

  \vspace{0.3in}
\end{itemize}

\setstretch{1.5}

\begin{itemize}
\tightlist
\item
  Interpret the confidence interval: We are \_\_\_\_\_\_\_\% \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ that, in the \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_, the true probability (or proportion) of complications is between \_\_\_\_\_\_\_\_\_\_\_\_ and \_\_\_\_\_\_\_\_\_.
\end{itemize}

\vspace{0.3in}

\setstretch{1}

\subsection*{Video: Bootstrap Confidence Intervals for One Categorical Variable (section 14.2)}\label{video-bootstrap-confidence-intervals-for-one-categorical-variable-section-14.2}
\addcontentsline{toc}{subsection}{Video: Bootstrap Confidence Intervals for One Categorical Variable (section 14.2)}

Review the Medical Consultant study from section 14.2.

Bootstrap distribution:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{216}\NormalTok{)}
\FunctionTok{one\_proportion\_bootstrap\_CI}\NormalTok{(}\AttributeTok{sample\_size =} \DecValTok{62}\NormalTok{, }\CommentTok{\# Sample size}
                    \AttributeTok{number\_successes =} \DecValTok{3}\NormalTok{, }\CommentTok{\# Observed number of successes}
                    \AttributeTok{number\_repetitions =} \DecValTok{10000}\NormalTok{, }\CommentTok{\# Number of bootstrap samples to use}
                    \AttributeTok{confidence\_level =} \FloatTok{0.95}\NormalTok{) }\CommentTok{\# Confidence level as a decimal}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=0.7\linewidth]{03-VN03-EDA_OneCatSimulation_files/figure-latex/unnamed-chunk-9-1} \end{center}

Confidence interval interpretation:

\begin{itemize}
\item
  How confident you are (e.g., 90\%, 95\%, 98\%, 99\%)
\item
  Parameter of interest
\item
  Calculated interval
\end{itemize}

\vspace{0.8in}

\subsubsection*{How does changing the confidence level impact the width of the confidence interval?}\label{how-does-changing-the-confidence-level-impact-the-width-of-the-confidence-interval}
\addcontentsline{toc}{subsubsection}{How does changing the confidence level impact the width of the confidence interval?}

90\% Confidence Interval:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{216}\NormalTok{)}
\FunctionTok{one\_proportion\_bootstrap\_CI}\NormalTok{(}\AttributeTok{sample\_size =} \DecValTok{62}\NormalTok{, }\CommentTok{\# Sample size}
                    \AttributeTok{number\_successes =} \DecValTok{3}\NormalTok{, }\CommentTok{\# Observed number of successes}
                    \AttributeTok{number\_repetitions =} \DecValTok{10000}\NormalTok{, }\CommentTok{\# Number of bootstrap samples to use}
                    \AttributeTok{confidence\_level =} \FloatTok{0.90}\NormalTok{) }\CommentTok{\# Confidence level as a decimal}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=0.7\linewidth]{03-VN03-EDA_OneCatSimulation_files/figure-latex/unnamed-chunk-10-1} \end{center}

99\% Confidence Interval:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{216}\NormalTok{)}
\FunctionTok{one\_proportion\_bootstrap\_CI}\NormalTok{(}\AttributeTok{sample\_size =} \DecValTok{62}\NormalTok{, }\CommentTok{\# Sample size}
                    \AttributeTok{number\_successes =} \DecValTok{3}\NormalTok{, }\CommentTok{\# Observed number of successes}
                    \AttributeTok{number\_repetitions =} \DecValTok{10000}\NormalTok{, }\CommentTok{\# Number of bootstrap samples to use}
                    \AttributeTok{confidence\_level =} \FloatTok{0.99}\NormalTok{) }\CommentTok{\# Confidence level as a decimal}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=0.7\linewidth]{03-VN03-EDA_OneCatSimulation_files/figure-latex/unnamed-chunk-11-1} \end{center}

\subsection{Concept Check}\label{concept-check-2}

Be prepared for group discussion in the next class. One member from the table should write the answers to the following on the whiteboard.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  What is the summary measure calculated from a single categorical variable?
\end{enumerate}

\vspace{0.3in}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Write the alternative hypothesis for the Martian Alphabet study in notation? How was the direction of the alternative hypothesis determined?
\end{enumerate}

\vspace{0.4in}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Do the results of the confidence interval for the Medical Consultant study \emph{match} the results based on the p-value?
\end{enumerate}

\vspace{0.5in}

\newpage

\section{Activity 4: Helper-Hinderer Part 1 --- Simulation-based Hypothesis Test}\label{activity-4-helper-hinderer-part-1-simulation-based-hypothesis-test}

\setstretch{1}

\subsection{Learning outcomes}\label{learning-outcomes-3}

\begin{itemize}
\item
  Identify the two possible explanations (one assuming the null hypothesis and one assuming the alternative hypothesis) for a relationship seen in sample data.
\item
  Given a research question involving a single categorical variable, construct the null and alternative hypotheses
  in words and using appropriate statistical symbols.
\item
  Describe and perform a simulation-based hypothesis test for a single proportion.
\end{itemize}

\subsection{Terminology review}\label{terminology-review-3}

In today's activity, we will work through a simulation-based hypothesis testing for a single categorical variable. Some terms covered in this activity are:

\begin{itemize}
\item
  Parameter of interest
\item
  Null hypothesis
\item
  Alternative hypothesis
\item
  Simulation
\end{itemize}

To review these concepts, see Chapters 9 \& 14 in your textbook.

\subsection{Steps of the statistical investigation process}\label{steps-of-the-statistical-investigation-process-1}

We will work through a five-step process to complete a hypothesis test for a single proportion.

\begin{itemize}
\item
  \textbf{Ask a research question} that can be addressed by collecting data. What are the researchers trying to show?
\item
  \textbf{Design a study and collect data}. This step involves selecting the people or objects to be studied and how to gather relevant data on them.
\item
  \textbf{Summarize and visualize the data}. Calculate summary statistics and create graphical plots that best represent the research question.
\item
  \textbf{Use statistical analysis methods to draw inferences from the data}. Choose a statistical inference method appropriate for the data and identify the p-value and/or confidence interval after checking assumptions. In this study, we will focus on using randomization to generate a simulated p-value.
\item
  \textbf{Communicate the results and answer the research question}. Using the p-value and confidence interval from the analysis, determine whether the data provide statistical evidence against the null hypothesis. Write a conclusion that addresses the research question.
\end{itemize}

\newpage

\subsection*{Notes on one categorical variable}\label{notes-on-one-categorical-variable}
\addcontentsline{toc}{subsection}{Notes on one categorical variable}

\vspace{2in}

\subsection{Helper-Hinderer}\label{helper-hinderer}

A study by Hamblin, Wynn, and Bloom reported in Nature (Hamblin et al. 2007) was intended to check young kids' feelings about helpful and non-helpful behavior. Non-verbal infants ages 6 to 10 months were shown short videos with different shapes either helping or hindering the climber. As a class we will watch this short video to see how the experiment was run: \url{https://youtu.be/anCaGBsBOxM}. Researchers were hoping to assess: Are non-verbal infants more likely to choose the helper toy? In the study, of the 16 infants age 6 to 10 months, 14 chose the \emph{helper} toy and 2 chose the \emph{hinderer} toy.

\vspace{2mm}

\begin{itemize}
\tightlist
\item
  Observational units:
\end{itemize}

\vspace{2mm}

\begin{itemize}
\item
  Variable:

  \begin{itemize}
  \tightlist
  \item
    Success:
  \end{itemize}
\end{itemize}

\vspace{2mm}

\subsubsection*{Ask a research question}\label{ask-a-research-question}
\addcontentsline{toc}{subsubsection}{Ask a research question}

\begin{itemize}
\tightlist
\item
  Research question:
\end{itemize}

\vspace{0.2in}

\subsubsection*{Design a study and collect data}\label{design-a-study-and-collect-data}
\addcontentsline{toc}{subsubsection}{Design a study and collect data}

Before using statistical inference methods, we must check that the cases are independent. The sample observations are independent if the outcome of one observation does not influence the outcome of another. One way this condition is met is if data come from a simple random sample of the target population.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Are the cases independent? Justify your answer.
\end{enumerate}

\vspace{0.8in}

\subsubsection*{R Instructions}\label{r-instructions}
\addcontentsline{toc}{subsubsection}{R Instructions}

For almost all activities and labs it will be necessary to upload the provided R script file from Canvas for that day. Your instructor will highlight a few steps in uploading files to and using RStudio.

The following are the steps to upload the necessary R script file for this activity:

\begin{itemize}
\item
  Download the Activity R script file from Canvas.
\item
  Click ``Upload'' in the ``Files'' tab in the bottom right window of RStudio. In the pop-up window, click ``Choose File'', and navigate to the folder where the Activity R script file is saved (most likely in your downloads folder). Click ``Open''; then click ``Ok''.
\item
  You should see the uploaded file appear in the list of files in the bottom right window. Click on the file name to open the file in the Editor window (upper left window).
\end{itemize}

Notice that the first three lines of code contain a prompt called \texttt{library}. Packages needed to run functions in R are stored in directories called libraries. When using the MSU RStudio server, all the packages needed for the class are already installed. We simply must tell R which packages we need for each R script file. We use the prompt \texttt{library} to load each \textbf{package} (or library) needed for each activity. Note, these \texttt{library} lines MUST be run each time you open a R script file in order for the functions in R to work.

\begin{itemize}
\tightlist
\item
  Highlight and run lines 1--3 to load the packages needed for this activity. Notice the use of the \# symbol in the R script file. This symbol is not part of the R code. It is used by these authors to add comments to the R code and explain what each call is telling the program to do.
\end{itemize}

R will ignore everything after a \# symbol when executing the code. Refer to the instructions following the \# symbol to understand what you need to enter in the code.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(catstats)}
\end{Highlighting}
\end{Shaded}

Throughout activities, we will often include the R code you would use in order to produce output or plots. These ``code chunks'' appear in gray. In the code chunk below, we demonstrate how to read the data set into R using the \texttt{read.csv()} function. The line of code shown below (line 7 in the R script file) reads in the data set and names the data set \texttt{infants}.

\subsubsection*{Summarize and visualize the data}\label{summarize-and-visualize-the-data}
\addcontentsline{toc}{subsubsection}{Summarize and visualize the data}

The following code reads in the data set and gives the number of infants in each level of the variable, whether the infant chose the helper or the hinderer.

\begin{itemize}
\tightlist
\item
  Highlight and run lines 7 and 8 to check that you get the same counts as shown below
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
 \CommentTok{\# Read in data set}
\NormalTok{infants }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"https://math.montana.edu/courses/s216/data/infantchoice.csv"}\NormalTok{)}
\NormalTok{infants }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{count}\NormalTok{(choice)  }\CommentTok{\# Count number in each choice category}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
#>     choice  n
#> 1   helper 14
#> 2 hinderer  2
\end{verbatim}

The following formula is used to calculate the proportion of successes in the sample.

\[\hat{p} = \frac{\mbox{number of successes}}{\mbox{total number of observational units}}\]
\vspace{1mm}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Using the R output and the formula given, calculate the summary statistic (sample proportion) to represent the research question. Recall that \texttt{choosing\ the\ helper\ toy} is a considered a success. Use appropriate notation.
\end{enumerate}

\vspace{0.5in}

\newpage

To visually display this data we can use either a frequency bar plot or a relative frequency bar plot.

\begin{itemize}
\item
  Enter the variable name \texttt{choice} for \texttt{variable} in the R code to create the frequency bar plot.
\item
  Note the name of the title is given in line 16 and includes the \textbf{type of plot}, \textbf{observational units}, and \textbf{variable name}.
\item
  Highlight and run lines 13--19 to create the plot
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{infants }\SpecialCharTok{\%\textgreater{}\%} \CommentTok{\# Data set piped into...}
    \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ variable)) }\SpecialCharTok{+}   \CommentTok{\# This specifies the variable}
    \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{stat =} \StringTok{"count"}\NormalTok{) }\SpecialCharTok{+}  \CommentTok{\# Tell it to make a bar plot}
    \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Frequency Bar Plot of Toy Choice for Pre{-}verbal Infants ages 6 to 10 months"}\NormalTok{,  }
       \CommentTok{\# Give your plot a title}
       \AttributeTok{x =} \StringTok{"Toy Choice"}\NormalTok{,   }\CommentTok{\# Label the x axis}
       \AttributeTok{y =} \StringTok{"Frequency"}\NormalTok{)  }\CommentTok{\# Label the y axis}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Sketch the frequency bar plot created below.
\end{enumerate}

\vspace{1.8in}

We could also choose to display the data as a proportion in a \textbf{relative frequency} bar plot. To find the relative frequency, the count in each level of \texttt{choice} is divided by the sample size. This calculation is the sample proportion for each level of \texttt{choice}. Notice that in the following code we told R to create a bar plot with proportions.

\begin{itemize}
\tightlist
\item
  In the R script file, highlight and run lines 23--29 to create the relative frequency bar plot.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{infants }\SpecialCharTok{\%\textgreater{}\%} \CommentTok{\# Data set piped into...}
    \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ choice)) }\SpecialCharTok{+}   \CommentTok{\# This specifies the variable}
    \FunctionTok{geom\_bar}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =} \FunctionTok{after\_stat}\NormalTok{(prop), }\AttributeTok{group =} \DecValTok{1}\NormalTok{)) }\SpecialCharTok{+}  \CommentTok{\# Tell it to make a bar plot with proportions}
    \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Relative Frequency Bar Plot of Toy }\SpecialCharTok{\textbackslash{}n}\StringTok{ Choice for Pre{-}verbal Infants ages 6 to 10 months"}\NormalTok{,  }
       \CommentTok{\# Give your plot a title}
       \AttributeTok{x =} \StringTok{"Toy Choice"}\NormalTok{,   }\CommentTok{\# Label the x axis}
       \AttributeTok{y =} \StringTok{"Relative Frequency"}\NormalTok{)  }\CommentTok{\# Label the y axis}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=0.5\linewidth]{03-A04-inference-1cat_test-simulation_files/figure-latex/unnamed-chunk-4-1} \end{center}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  Which features in the relative frequency bar plot are the same as the frequency bar plot? Which are different?
\end{enumerate}

\vspace{0.5in}

We cannot assess whether infants are more likely to choose the helper toy based on the statistic and plot alone. The next step is to analyze the data by using a hypothesis test to discover if there is evidence against the null hypothesis.

\subsubsection*{Use statistical analysis methods to draw inferences from the data}\label{use-statistical-analysis-methods-to-draw-inferences-from-the-data}
\addcontentsline{toc}{subsubsection}{Use statistical analysis methods to draw inferences from the data}

\subsubsection*{Notes on hypotheses tests}\label{notes-on-hypotheses-tests}
\addcontentsline{toc}{subsubsection}{Notes on hypotheses tests}

\vspace{2in}

When performing a hypothesis test, we must first identify the null hypothesis. The null hypothesis is written about the parameter of interest, or the value that summarizes the variable in the population.

The parameter of interest is a statement about what we want to find about the population. The following must be included when writing the parameter of interest.

\begin{itemize}
\item
  Population word (true, long-run, population)
\item
  Summary measure (depends on the type of data)
\item
  Context

  \begin{itemize}
  \item
    Observational units
  \item
    Variable(s)
  \end{itemize}
\end{itemize}

\textbf{Parameter of interest:}

\vspace{0.5in}

If the children are just randomly choosing the toy, we would expect half (0.5) of the infants to choose the helper toy. This is the null value for our study.

\textbf{Null Hypothesis (in words):}

\vspace{0.5in}

The notation used for a population proportion (or probability, or true proportion) is \(\pi\). Since this summarizes a population, it is a parameter. When writing the \textbf{null hypothesis} in notation, we set the parameter equal to the null value, \(H_0: \pi = \pi_0\).

\textbf{Null Hypothesis (in notation):}

\vspace{0.5in}

The \textbf{alternative hypothesis} is the claim to be tested and the direction of the claim (less than, greater than, or not equal to) is based on the research question.

\begin{itemize}
\tightlist
\item
  Based on the research question from question 1, are we testing that the parameter is greater than 0.5, less than 0.5 or different than 0.5?
\end{itemize}

\vspace{0.2in}

\textbf{Alternative hypothesis (in words):}

\vspace{0.5in}

\textbf{Alternative hypothesis (in notation):}

\vspace{0.5in}

Remember that when utilizing a hypothesis test, we are evaluating two competing possibilities. For this study the \textbf{two possibilities} are either\ldots{}

\begin{itemize}
\item
  The true proportion of infants who choose the helper is 0.5 and our results just occurred by random chance; or,
\item
  The true proportion of infants who choose the helper is greater than 0.5 and our results reflect this.
\end{itemize}

Notice that these two competing possibilities represent the null and alternative hypotheses.

We will now simulate one sample of a \textbf{null distribution} of sample proportions. The null distribution is created under the assumption the null hypothesis is true. In this case, we assume the true proportion of infants who choose the helper is 0.5, so we will create 10000 (or more) different simulations of 16 infants under this assumption.

Let's think about how to use a coin to create one simulation of 16 infants under the assumption the null hypothesis is true. Let heads equal infant chose the helper toy and tails equal infant chose the hinderer toy.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  How many times would you flip a coin to simulate the sample of infants?
\end{enumerate}

\vspace{0.2in}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{5}
\tightlist
\item
  Flip a coin 16 times recording the number of times the coin lands on heads. This represents one simulated sample of 16 infants randomly choosing the toy. Calculate the proportion of coin flips that resulted in heads.
\end{enumerate}

\vspace{0.2in}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{6}
\tightlist
\item
  Is the value from question 6 closer to 0.5, the null value, or closer to the sample proportion, 0.875?
\end{enumerate}

\vspace{0.2in}

Report the number of coin flips you got as indicated by your instructor.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{7}
\tightlist
\item
  Sketch the graph created by your instructor of each student's proportion of heads out of 16 coin flips.
\end{enumerate}

\vspace{2in}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{8}
\tightlist
\item
  Circle the observed statistic (value from question 2) on the distribution shown above. Where does this statistic fall in this distribution: Is it near the center of the distribution (near 0.5) or in one of the tails of the distribution?
\end{enumerate}

\vspace{0.2in}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{9}
\tightlist
\item
  Is the observed statistic likely to happen or unlikely to happen if the true proportion of infants who choose the helper is 0.5? Explain your answer using the plot.
\end{enumerate}

\vspace{0.8in}

In the next class, we will continue to assess the strength of evidence against the null hypothesis by using a computer to simulate 10000 samples when we assume the null hypothesis is true.

\subsection{Take-home messages}\label{take-home-messages-3}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Two types of plots are used for plotting categorical variables: frequency bar plots, relative frequency bar plots.
\item
  In a hypothesis test we have two competing hypotheses, the null hypothesis and the alternative hypothesis. The null hypothesis represents either a skeptical perspective or a perspective of no difference or no effect. The alternative hypothesis represents a new perspective such as the possibility that there has been a change or that there is a treatment effect in an experiment.
\item
  In a simulation-based test, we create a distribution of possible simulated statistics for our sample if the null hypothesis is true. Then we see if the calculated observed statistic from the data is likely or unlikely to occur when compared to the null distribution.
\item
  To create one simulated sample on the null distribution for a sample proportion, spin a spinner with probability equal to \(\pi_0\) (the null value), \(n\) times or draw with replacement \(n\) times from a deck of cards created to reflect \(\pi_0\) as the probability of success. Calculate and plot the proportion of successes from the simulated sample.
\end{enumerate}

\subsection{Additional notes}\label{additional-notes-3}

Activities 4--6 cover the material in Module 3. Use this space to summarize your thoughts and take additional notes on today's activity and material covered.

\newpage

\section{Activity 5: Helper-Hinderer (continued)}\label{activity-5-helper-hinderer-continued}

\setstretch{1}

\subsection{Learning outcomes}\label{learning-outcomes-4}

\begin{itemize}
\item
  Describe and perform a simulation-based hypothesis test for a single proportion.
\item
  Interpret and evaluate a p-value for a simulation-based hypothesis test for a single proportion.
\item
  Explore what a p-value represents
\end{itemize}

\subsection{Steps of the statistical investigation process}\label{steps-of-the-statistical-investigation-process-2}

In today's activity we will continue with steps 4 and 5 in the statistical investigation process. We will continue to assess the Helper-Hinderer study from last class.

\begin{itemize}
\item
  \textbf{Ask a research question} that can be addressed by collecting data. What are the researchers trying to show?
\item
  \textbf{Design a study and collect data}. This step involves selecting the people or objects to be studied and how to gather relevant data on them.
\item
  \textbf{Summarize and visualize the data}. Calculate summary statistics and create graphical plots that best represent the research question.
\item
  \textbf{Use statistical analysis methods to draw inferences from the data}. Choose a statistical inference method appropriate for the data and identify the p-value and/or confidence interval after checking assumptions. In this study, we will focus on using randomization to generate a simulated p-value.
\item
  \textbf{Communicate the results and answer the research question}. Using the p-value and confidence interval from the analysis, determine whether the data provide statistical evidence against the null hypothesis. Write a conclusion that addresses the research question.
\end{itemize}

\subsection{Helper-Hinderer}\label{helper-hinderer-1}

In class today, we will revisit the study on infants as described below.

A study by Hamblin, Wynn, and Bloom reported in Nature (Hamblin et al. 2007) was intended to check young kids' feelings about helpful and non-helpful behavior. Non-verbal infants ages 6 to 10 months were shown short videos with different shapes either helping or hindering the climber. As a class we will watch this short video to see how the experiment was run: \url{https://youtu.be/anCaGBsBOxM}. Researchers were hoping to assess: Are non-verbal infants more likely to choose the helper toy? In the study, of the 16 infants age 6 to 10 months, 14 chose the \emph{helper} toy and 2 chose the \emph{hinderer} toy.

\subsubsection*{Sampling distribution of the sample proportion.}\label{sampling-distribution-of-the-sample-proportion.}
\addcontentsline{toc}{subsubsection}{Sampling distribution of the sample proportion.}

The sampling distribution is a distribution of a statistic from all possible samples of size \(n\) from the population. The mean of the sampling distribution should be close to the parameter value and the standard deviation of the sampling distribution will estimate the variability of statistics from sample to sample.

To create a sampling distribution of the statistic, we would take infinite samples of size \(n\) from the population and plot the statistic from each sample. To illustrate this idea we will revisit the Becenti address looking at the mean word length.

\begin{verbatim}
#>   min Q1 median Q3 max     mean       sd   n missing
#> 1   1  2      3  5  14 3.952646 2.300228 359       0
\end{verbatim}

\begin{center}\includegraphics[width=0.7\linewidth]{03-A05-inference-1cat_simulation-continued_files/figure-latex/unnamed-chunk-2-1} \end{center}

Note that the mean of this small population (\(N=359\)) is 3.9526. Typically, we don't have such small population sizes so we need a way to simulate the sampling distribution of the statistic to estimate the sample to sample variability. Repeat samples of size 10 are taken from the population of words and the sample mean of each sample is plotted below.

\begin{verbatim}
#>   min  Q1 median  Q3 max     mean        sd   n missing
#> 1 2.1 3.3    3.9 4.4 6.7 3.934557 0.7954711 305       0
\end{verbatim}

\begin{center}\includegraphics[width=0.7\linewidth]{03-A05-inference-1cat_simulation-continued_files/figure-latex/unnamed-chunk-3-1} \end{center}

The mean of this simulated distribution is 3.934557, which is close to the true mean from the population. The standard deviation is 0.7954711 - this measures how far each statistic is from the true mean word length, on average. Later in the semester, we will learn how this variability is affected by the sample size.

Today, we will use the computer to simulate the sampling distribution of the sample proportion by creating a null distribution of 10000 different samples of 16 infants, plotting the proportion who will choose the helper in each sample, based on the assumption that the true proportion of infants who choose the helper is 0.5 (or that the null hypothesis is true).

\newpage

To use the computer simulation, we will need to enter the

\begin{itemize}
\tightlist
\item
  assumed ``probability of success'' (\(\pi_0\)),
\item
  ``sample size'' (the number of observational units or cases in the sample),
\item
  ``number of repetitions'' (the number of samples to be generated - typically we use 10000),
\item
  ``as extreme as'' (the observed statistic), and
\item
  the ``direction'' (matches the direction of the alternative hypothesis).
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  What values should be entered for each of the following into the one proportion test to create 10000 simulations?
\end{enumerate}

\vspace{1mm}

\begin{itemize}
\tightlist
\item
  Probability of success (null value):
\end{itemize}

\vspace{.2in}

\begin{itemize}
\tightlist
\item
  Sample size (n):
\end{itemize}

\vspace{.2in}

\begin{itemize}
\tightlist
\item
  Number of repetitions (typically use 10000 simulations):
\end{itemize}

\vspace{.2in}

\begin{itemize}
\tightlist
\item
  As extreme as (value of statistic):
\end{itemize}

\vspace{.2in}

\begin{itemize}
\tightlist
\item
  Direction (\texttt{"greater"}, \texttt{"less"}, or \texttt{"two-sided"}):
\end{itemize}

The following shows one possible distribution of simulated sample proportions assuming the null hypothesis, true proportion of non-verbal infants aged 6 to 10 months that will choose the helper toy is 0.5, is true.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{100}\NormalTok{)}
\FunctionTok{one\_proportion\_test}\NormalTok{(}\AttributeTok{probability\_success =} \FloatTok{0.5}\NormalTok{, }\CommentTok{\# Null hypothesis value}
          \AttributeTok{sample\_size =} \DecValTok{16}\NormalTok{, }\CommentTok{\# Enter sample size}
          \AttributeTok{number\_repetitions =} \DecValTok{10000}\NormalTok{, }\CommentTok{\# Enter number of simulations}
          \AttributeTok{as\_extreme\_as =} \FloatTok{0.875}\NormalTok{, }\CommentTok{\# Observed statistic}
          \AttributeTok{direction =} \StringTok{"greater"}\NormalTok{, }\CommentTok{\# Specify direction of alternative hypothesis}
          \AttributeTok{summary\_measure =} \StringTok{"proportion"}\NormalTok{) }\CommentTok{\# Reporting proportion or number of successes?}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=0.7\linewidth]{03-A05-inference-1cat_simulation-continued_files/figure-latex/unnamed-chunk-4-1} \end{center}

\subsection*{Notes on the null distribution}\label{notes-on-the-null-distribution}
\addcontentsline{toc}{subsection}{Notes on the null distribution}

\newpage

Using R, we will use the \texttt{one\_proportion\_test()} function (in the \texttt{catstats} package) to simulate another null distribution of sample proportions and compute a p-value. Using the provided \texttt{R} script file, fill in the values/words for each \texttt{xx} with your answers from question 1 in the one proportion test to create a null distribution with 10000 simulations. Then highlight and run lines 1--16. \emph{Note that the value for the mean, standard deviation, and p-value changed slightly.}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{216}\NormalTok{)}
\FunctionTok{one\_proportion\_test}\NormalTok{(}\AttributeTok{probability\_success =} \FloatTok{0.5}\NormalTok{, }\CommentTok{\# Null hypothesis value}
          \AttributeTok{sample\_size =} \DecValTok{16}\NormalTok{, }\CommentTok{\# Enter sample size}
          \AttributeTok{number\_repetitions =} \DecValTok{10000}\NormalTok{, }\CommentTok{\# Enter number of simulations}
          \AttributeTok{as\_extreme\_as =} \FloatTok{0.875}\NormalTok{, }\CommentTok{\# Observed statistic}
          \AttributeTok{direction =} \StringTok{"greater"}\NormalTok{, }\CommentTok{\# Specify direction of alternative hypothesis}
          \AttributeTok{summary\_measure =} \StringTok{"proportion"}\NormalTok{) }\CommentTok{\# Reporting proportion or number of successes?}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=0.7\linewidth]{03-A05-inference-1cat_simulation-continued_files/figure-latex/unnamed-chunk-5-1} \end{center}

For the remainder of the questions in this activity use this 2nd simulated null distribution.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Circle the observed statistic (value calculated in Activity 4) on the null distribution. Where does this statistic fall in the null distribution: Is it near the center of the distribution (near 0.5) or in one of the tails of the distribution?
\end{enumerate}

\vspace{0.3in}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Is the observed statistic likely to happen or unlikely to happen if the true proportion of infants who choose the helper is 0.5? Explain your answer using the plot.
\end{enumerate}

\vspace{0.5in}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  Using the simulation, what is the proportion of simulated samples that generated a sample proportion at the observed statistic or greater, if the true proportion of infants who choose the helper is 0.5? \emph{Hint}: Look under the simulation.
\end{enumerate}

\vspace{0.3in}

\newpage

\subsection*{Notes on the p-value}\label{notes-on-the-p-value}
\addcontentsline{toc}{subsection}{Notes on the p-value}

The value in question 4 is the \textbf{p-value}. The smaller the p-value, the more evidence we have against the null hypothesis.

\vspace{0.2in}

\begin{center}\includegraphics[width=0.9\linewidth]{images/soe_gradient_gray} \end{center}

\subsubsection*{Interpret the p-value}\label{interpret-the-p-value}
\addcontentsline{toc}{subsubsection}{Interpret the p-value}

The p-value measures the probability that we observe a sample proportion as extreme as what was seen in the data or more extreme (matching the direction of the \(H_A\)) IF the null hypothesis is true. This is a conditional probability, calculated dependent on the null hypothesis being true. Represented in probability notation:

\[P(\text{statistic or more extreme|the null hypothesis is true})\]

\textbf{p-value interpretation:}

\vspace{1in}

\subsubsection*{Communicate the results and answer the research question}\label{communicate-the-results-and-answer-the-research-question}
\addcontentsline{toc}{subsubsection}{Communicate the results and answer the research question}

When we write a conclusion we answer the research question by stating how much evidence there is in support of the alternative hypothesis.

\textbf{Conclusion:}

\vspace{1in}

\subsubsection*{Generalization}\label{generalization}
\addcontentsline{toc}{subsubsection}{Generalization}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  To what group of observational units can the results be generalized to?
\end{enumerate}

\vspace{0.5in}

\subsection{Take-home messages}\label{take-home-messages-4}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  The null distribution is created based on the assumption the null hypothesis is true. We compare the sample statistic to the distribution to find the likelihood of observing this statistic.
\item
  The p-value measures the probability of observing the sample statistic or more extreme (in direction of the alternative hypothesis) if the null hypothesis is true.
\item
  The smaller the p-value of the test, the more evidence there is \textbf{against} the null hypothesis.
\end{enumerate}

\subsection{Additional notes}\label{additional-notes-4}

Activities 4--6 cover the material in Module 3. For more practice with simulation hypothesis testing of a single categorical variable use the Module 3 Review worksheet in the Unit 1 Review Materials (pgs. 112--115).

Use this space to summarize your thoughts and take additional notes on today's activity and material covered.

\newpage

\section{Activity 6: Helper-Hinderer --- Simulation-based Confidence Interval}\label{activity-6-helper-hinderer-simulation-based-confidence-interval}

\setstretch{1}

\subsection{Learning outcomes}\label{learning-outcomes-5}

\begin{itemize}
\item
  Use bootstrapping to find a confidence interval for a single proportion.
\item
  Interpret a confidence interval for a single proportion.
\end{itemize}

\subsection{Terminology review}\label{terminology-review-4}

In today's activity, we will introduce simulation-based confidence intervals for a single proportion. Some terms covered in this activity are:

\begin{itemize}
\item
  Parameter of interest
\item
  Bootstrapping
\item
  Confidence interval
\end{itemize}

To review these concepts, see Chapters 10 \& 14 in your textbook.

\subsection{Helper-Hinderer}\label{helper-hinderer-2}

In the last class, we found very strong evidence that the true proportion of infants who will choose the helper character is greater than 0.5. But what \emph{is} the true proportion of infants who will choose the helper character? We will use this same study to estimate this parameter of interest by creating a confidence interval.

As a reminder: A study by Hamblin, Wynn, and Bloom reported in Nature (Hamblin et al. 2007) was intended to check young kids' feelings about helpful and non-helpful behavior. Non-verbal infants ages 6 to 10 months were shown short videos with different shapes either helping or hindering the climber. Researchers were hoping to assess: Are non-verbal infants more likely to choose the helper toy? In the study, of the 16 infants age 6 to 10 months, 14 chose the \emph{helper} toy and 2 chose the \emph{hinderer} toy.

A \textbf{point estimate} (our observed statistic) provides a single plausible value for a parameter. However, a point estimate is rarely perfect; usually there is some error in the estimate. In addition to supplying a point estimate of a parameter, a next logical step would be to provide a plausible \emph{range} of values for the parameter. This plausible range of values for the population parameter is called an \textbf{interval estimate} or \textbf{confidence interval}.

\subsubsection*{Activity intro}\label{activity-intro}
\addcontentsline{toc}{subsubsection}{Activity intro}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  What is the value of the point estimate (sample statistic)?
\end{enumerate}

\vspace{0.3in}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  If we took another random sample of 16 infants, would we get the exact same point estimate? Explain why or why not.
\end{enumerate}

\vspace{0.5in}

In today's activity, we will use bootstrapping to find a 95\% confidence interval for \(\pi\), the parameter of interest.

\subsection*{Notes on Confidence Intervals}\label{notes-on-confidence-intervals}
\addcontentsline{toc}{subsection}{Notes on Confidence Intervals}

\vspace{2in}

\subsubsection*{Use statistical analysis methods to draw inferences from the data}\label{use-statistical-analysis-methods-to-draw-inferences-from-the-data-1}
\addcontentsline{toc}{subsubsection}{Use statistical analysis methods to draw inferences from the data}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Write out the parameter of interest in words, in context of the study. What does \(\pi\) represent?
\end{enumerate}

\vspace{0.5in}

To create the null distribution we flipped a coin 16 times to simulate infants randomly choosing the helper toy with a probability of 50\%.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  Why can't we use a coin to simulate the bootstrap distribution.
\end{enumerate}

\vspace{0.7in}

To create the bootstrap distribution.

\begin{itemize}
\item
  First we would label the cards to represent the sample statistic: 14 helper and 2 hinderer.
\item
  Sample with replacement 16 times
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  Using the cards provided by your instructor, create one bootstrap sample. Report your simulated sample proportion on the whiteboard.
\end{enumerate}

\vspace{0.3in}

To use the computer simulation to create a bootstrap distribution, we will need to enter the

\begin{itemize}
\tightlist
\item
  ``sample size'' (the number of observational units or cases in the sample),
\item
  ``number of successes'' (the number of cases that choose the helper character),
\item
  ``number of repetitions'' (the number of samples to be generated), and
\item
  the ``confidence level'' (which level of confidence are we using to create the confidence interval).
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{5}
\tightlist
\item
  What values should be entered for each of the following into the simulation to create the bootstrap distribution of sample proportions to find a 95\% confidence interval?
  \vspace{1mm}
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Sample size (n):
\end{itemize}

\vspace{.1in}

\begin{itemize}
\tightlist
\item
  Number of successes:
\end{itemize}

\vspace{.1in}

\begin{itemize}
\tightlist
\item
  Number of repetitions (at least 10000):
\end{itemize}

\vspace{.1in}

\begin{itemize}
\tightlist
\item
  Confidence level (as a decimal):
\end{itemize}

\vspace{.1in}

We will use the \texttt{one\_proportion\_bootstrap\_CI()} function in R (in the \texttt{catstats} package) to simulate the bootstrap distribution of sample proportions and calculate a confidence interval. Using the provided R script file, fill in the values/words for each \texttt{xx} with your answers from question 6 in the one proportion bootstrap confidence interval (CI) code to create a bootstrap distribution with 10000 simulations. Then highlight and run lines 1--9.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{one\_proportion\_bootstrap\_CI}\NormalTok{(}\AttributeTok{sample\_size =} \DecValTok{16}\NormalTok{, }\CommentTok{\# Sample size}
                    \AttributeTok{number\_successes =} \DecValTok{14}\NormalTok{, }\CommentTok{\# Observed number of successes}
                    \AttributeTok{number\_repetitions =} \DecValTok{10000}\NormalTok{, }\CommentTok{\# Number of bootstrap samples to use}
                    \AttributeTok{confidence\_level =} \FloatTok{0.95}\NormalTok{) }\CommentTok{\# Confidence level as a decimal}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=0.7\linewidth]{03-A06-inference-1cat_CI-simulation_files/figure-latex/unnamed-chunk-2-1} \end{center}

\subsubsection*{Notes on the bootstrap distribution}\label{notes-on-the-bootstrap-distribution}
\addcontentsline{toc}{subsubsection}{Notes on the bootstrap distribution}

\vspace{1.5in}

\textbf{95\% Confidence Interval:}

\textbf{Interpretation of the 95\% confidence interval in context.}

\vspace{.6in}

\subsubsection*{Communicate the results and answer the research question}\label{communicate-the-results-and-answer-the-research-question-1}
\addcontentsline{toc}{subsubsection}{Communicate the results and answer the research question}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{6}
\tightlist
\item
  Is the value 0.5 (the null value) in the 95\% confidence interval?
\end{enumerate}

\vspace{.2in}

~~~Explain how this indicates that the p-value provides strong evidence against the null.

\vspace{0.5in}

\newpage

\subsubsection*{Statistical Analysis Write-up}\label{statistical-analysis-write-up}
\addcontentsline{toc}{subsubsection}{Statistical Analysis Write-up}

In many of our studies we will write a paragraph summarizing the results of the study. The following is a summary paragraph for the infant study. The paragraph should include an introduction, the interpretation of the sample statistic, p-value and interpretation, confidence interval and interpretation, conclusion statement, and generalization.

\setstretch{1}

\textbf{An introduction including the observational units and variable(s) in the study and their role and type. The introduction should also include the sampling method and research question.}

\setstretch{3}

\leftskip=1cm

Researchers were interested if infants observe social cues and would be more likely to choose the helper toy. The observational units in this study are 16 non-verbal infants ages 6 to 10 months old. This is a convenience sample of infants. On each infant the researchers recorded whether or not the infant choose the helper toy. This is a categorical variable. Researchers were hoping to assess: Are non-verbal infants more likely to choose the helper toy?

\leftskip=0cm

\textbf{Report and interpret the sample statistic in context of the study.}

\leftskip=1cm

From the study, it was reported that the proportion of the 16 infants that chose the helper toy was 0.875.

\leftskip=0cm

\textbf{Report how the p-value was found. Include an interpretation of the p-value.}

\leftskip=1cm

A simulation null distribution with 10000 simulations was created in RStudio. The p-value was found by calculating the proportion of simulations in the null distribution at the sample statistic of 0.875 and greater. This resulted in a p-value of 0.0026. We would observe a sample proportion of 0.875 or greater with a probability of 0.0026, IF we assume the true proportion of non-verbal infants age 6 to 10 months who would choose the helper toy is 0.5.

\leftskip=0cm

\newpage

\textbf{Report and interpret the confidence interval.}

\leftskip=1cm

In addition, a 95\% confidence interval was found for the parameter of interest. We are 95\% confident that the true proportion of non-verbal infants age 6 to 10 months who will choose the helper toy is between 0.688 and 1.

\leftskip=0cm

\textbf{Write a conclusion for the study.}

\leftskip=1cm

Based on the p-value of 0.0026, there is very strong evidence that the true proportion of non-verbal infants age 6 to 10 months who will choose the helper toy is greater than 0.5.

\leftskip=0cm

\vspace{0.2in}

\setstretch{1}

\textbf{And last, report the scope of inference for the study. Since there is only a single categorical variable in this study, we only need to discuss generalization.}

\setstretch{3}

\leftskip=1cm

The results of this study can be generalized to the sample of non-verbal infants or similar observational units as the researchers did not select a random sample.

\setstretch{1}

\newpage

\subsection{Take-home messages}\label{take-home-messages-5}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  The goal in a hypothesis test is to assess the strength of evidence for an effect, while the goal in creating a confidence interval is to determine how large the effect is. A \textbf{confidence interval} is a range of \emph{plausible} values for the parameter of interest.
\item
  In simulation-based methods (bootstrapping), a simulated distribution of possible sample statistics is created showing the possible sample-to-sample variability. Then we find the middle \(X\) percent of the distribution around the sample statistic using the percentile method to give the range of values for the confidence interval. This shows us that we are \(X\)\% confident that the parameter is within this range, where \(X\) represents the level of confidence.
\item
  When the null value is within the confidence interval, it is a plausible value for the parameter of interest; thus, we would find a larger p-value for a hypothesis test of that null value. Conversely, if the null value is NOT within the confidence interval, we would find a small p-value for the hypothesis test and strong evidence against this null hypothesis.
\item
  To create one simulated sample on the bootstrap distribution for a sample proportion, label \(n\) cards with the original responses. Draw with replacement \(n\) times. Calculate and plot the resampled proportion of successes.
\end{enumerate}

\subsection{Additional notes}\label{additional-notes-5}

Activities 4--6 cover the material in Module 3. For more practice with simulation confidence intervals for a single categorical variable use the Module 3 Review worksheet in the Unit 1 Review Materials (pgs. 112--115).

Use this space to summarize your thoughts and take additional notes on today's activity and material covered.

\newpage

\section{Golden Ticket to Descriptive and Inferential Statistical Methods}\label{golden-ticket-to-descriptive-and-inferential-statistical-methods}

In this course, we have covered descriptive (summary statistics and plots) and inferential (hypothesis tests and confidence intervals) methods for five different scenarios:

\begin{itemize}
\tightlist
\item
  one categorical response variable (Module 3 \& 4)
\item
  one quantitative response variable (Module 6 \& 7) or paired differences in a quantitative variable (Module 12)
\item
  two categorical variables (Module 8 \& 9)
\item
  one quantitative response variable and one categorical explanatory variable (Module 11)
\item
  two quantitative variables (Module 13)
\end{itemize}

The ``golden ticket'' shown on the next page presents a visual summary of the similarities and differences across these five scenarios.

\includepdf[landscape=true]{GoldenTicket_F26.pdf}

\chapter*{References}\label{references}
\addcontentsline{toc}{chapter}{References}

\protect\phantomsection\label{refs}
\begin{CSLReferences}{1}{1}
\bibitem[\citeproctext]{ref-pga}
\emph{Average Driving Distance and Fairway Accuracy}. 2008. \href{https://www.pga.com/\%20and\%20https://www.lpga.com/}{https://www.pga.com/ and https://www.lpga.com/}.

\bibitem[\citeproctext]{ref-banton2022}
{Banton, et al, S.} 2022. {``Jog with Your Dog: Dog Owner Exercise Routines Predict Dog Exercise Routines and Perception of Ideal Body Weight.''} \emph{PLoS ONE} 17(8).

\bibitem[\citeproctext]{ref-bhavsar2022}
{Bhavsar, et al, A.} 2022. {``Increased Risk of Herpes Zoster in Adults \(\geq\)50 Years Old Diagnosed with COVID-19 in the United States.''} \emph{Open Forum Infectious Diseases} 9(5).

\bibitem[\citeproctext]{ref-islands}
Bulmer, M. n.d. \emph{Islands in Schools Project}. \url{https://sites.google.com/site/islandsinschoolsprojectwebsite/home}.

\bibitem[\citeproctext]{ref-bts}
\emph{Bureau of Transportation Statistics}. 2019. \url{https://www.bts.gov/}.

\bibitem[\citeproctext]{ref-babies}
\emph{Child Health and Development Studies}. n.d. \url{https://www.chdstudies.org/}.

\bibitem[\citeproctext]{ref-darley1973}
Darley, J. M., and C. D. Batson. 1973. {``"From Jerusalem to Jericho": A Study of Situational and Dispositional Variables in Helping Behavior.''} \emph{Journal of Personality and Social Psychology} 27: 100--108.

\bibitem[\citeproctext]{ref-davis2020}
Davis, Smith, A. K. 2020. {``A Poor Substitute for the Real Thing: Captive-Reared Monarch Butterflies Are Weaker, Paler and Have Less Elongated Wings Than Wild Migrants.''} \emph{Biology Letters} 16.

\bibitem[\citeproctext]{ref-doit2015}
{Du Toit, et al, G.} 2015. {``Randomized Trial of Peanut Consumption in Infants at Risk for Peanut Allergy.''} \emph{New England Journal of Medicine} 372.

\bibitem[\citeproctext]{ref-edmunds2016}
{Edmunds, et al, D.} 2016. {``Chronic Wasting Disease Drives Population Decline of White-Tailed Deer.''} \emph{PLoS ONE} 11(8).

\bibitem[\citeproctext]{ref-ipeds}
Education Statistics, National Center for. 2018. \emph{IPEDS}. \url{https://nces.ed.gov/ipeds/}.

\bibitem[\citeproctext]{ref-gbmarried}
\emph{Great Britain Married Couples: Great Britain Office of Population Census and Surveys}. n.d. \url{https://discovery.nationalarchives.gov.uk/details/r/C13351}.

\bibitem[\citeproctext]{ref-zeitler2012}
Group, TODAY Study. 2012. {``\href{https://www.ncbi.nlm.nih.gov/pubmed/22540912}{A Clinical Trial to Maintain Glycemic Control in Youth with Type 2 Diabetes}.''} \emph{New England Journal of Medicine} 366: 2247--56.

\bibitem[\citeproctext]{ref-hamblin2007}
Hamblin, J. K., K. Wynn, and P. Bloom. 2007. {``Social Evaluation by Preverbal Infants.''} \emph{Nature} 450 (6288): 557--59.

\bibitem[\citeproctext]{ref-hirschfelder2018}
Hirschfelder, A., and P. F. Molin. 2018. \emph{I Is for Ignoble: Stereotyping Native Americans.} \href{Retrieved\%20from\%20https://www.ferris.edu/HTMLS/news/jimcrow/native/homepage.htm.}{Retrieved from https://www.ferris.edu/HTMLS/news/jimcrow/native/homepage.htm.}

\bibitem[\citeproctext]{ref-hutchison2013}
Hutchison, R. L., and M. A. Hirthler. 2013. {``\href{https://www.ncbi.nlm.nih.gov/pubmed/23932117}{Upper Extremity Injuies in Homer's Iliad}.''} \emph{Journal of Hand Surgery (American Volume)} 38: 1790--93.

\bibitem[\citeproctext]{ref-imdb}
\emph{{IMDb} Movies Extensive Dataset}. 2016. \url{https://kaggle.com/stefanoleone992/imdb-extensive-dataset}.

\bibitem[\citeproctext]{ref-kalra2022}
{Kalra, et al., Dl.} 2022. \emph{Trustworthiness of Indian Youtubers}. Kaggle. \url{https://doi.org/10.34740/KAGGLE/DSV/4426566}.

\bibitem[\citeproctext]{ref-keating2021}
Keating, D., N. Ahmed, F. Nirappil, Stanley-Becker I., and L. Bernstein. 2021. {``Coronavirus Infections Dropping Where People Are Vaccinated, Rising Where They Are Not, Post Analysis Finds.''} \emph{Washington Post}. \url{https://www.washingtonpost.com/health/2021/06/14/covid-cases-vaccination-rates/}.

\bibitem[\citeproctext]{ref-laeng2007}
Laeng, Mathisen, B. 2007. {``Why Do Blue-Eyed Men Prefer Women with the Same Eye Color?''} \emph{Behavioral Ecology and Sociobiology} 61(3).

\bibitem[\citeproctext]{ref-levin2000}
Levin, D. T. 2000. {``Race as a Visual Feature: Using Visual Search and Perceptual Discrimination Tasks to Understand Face Categories and the Cross-Race Recognition Deficit.''} \emph{Journal of Experimental Psychology} 129(4).

\bibitem[\citeproctext]{ref-luetkemeier2017}
{LUETKEMEIER, et al., M.} 2017. {``Skin Tattoos Alter Sweat Rate and Na+ Concentration.''} \emph{Medicine and Science in Sports and Exercise} 49(7).

\bibitem[\citeproctext]{ref-madden2020}
{Madden, et al, J.} 2020. {``Ready Student One: Exploring the Predictors of Student Learning in Virtual Reality.''} \emph{PLoS ONE} 15(3).

\bibitem[\citeproctext]{ref-miller1956}
Miller, G. A. 1956. {``The Magical Number Seven, Plus or Minus Two: Some Limits on Our Capacity for Processing Information.''} \emph{Psychological Review} 63(2).

\bibitem[\citeproctext]{ref-becentispeech}
Moquin, W., and C. Van Doren. 1973. \emph{Great Documents in American Indian History}. Praeger.

\bibitem[\citeproctext]{ref-pew2022}
\emph{More Americans Are Joining the 'Cashless' Economy}. 2022. \url{https://www.pewresearch.org/short-reads/2022/10/05/more-americans-are-joining-the-cashless-economy/.}

\bibitem[\citeproctext]{ref-weather}
National Weather Service Corporate Image Web Team. n.d. \emph{National Weather Service -- {NWS} Billings}. \url{https://w2.weather.gov/climate/xmacis.php?wfo=byz}.

\bibitem[\citeproctext]{ref-obrien2019}
O'Brien, Lynch, H. D. 2019. {``Crocodylian Head Width Allometry and Phylogenetic Prediction of Body Size in Extinct Crocodyliforms.''} \emph{Integrative Organismal Biology} 1.

\bibitem[\citeproctext]{ref-ocean}
\emph{Ocean Temperature and Salinity Study}. n.d. \url{https://calcofi.org/}.

\bibitem[\citeproctext]{ref-WashPost2022}
\emph{Older People Who Get Covid Are at Increased Risk of Getting Shingles}. 2022. \url{https://www.washingtonpost.com/health/2022/04/19/shingles-and-covid-over-50/.}

\bibitem[\citeproctext]{ref-physhealth}
\emph{Physician's Health Study}. n.d. \url{https://phs.bwh.harvard.edu/}.

\bibitem[\citeproctext]{ref-porath2017}
Porath, Erez, C. 2017. {``Does Rudeness Really Matter? The Effects of Rudeness on Task Performance and Helpfulness.''} \emph{Academy of Management Journal} 50.

\bibitem[\citeproctext]{ref-quinn1999}
Quinn, G. E., C. H. Shin, M. G. Maguire, and R. A. Stone. 1999. {``Myopia and Ambient Lighting at Night.''} \emph{Nature} 399 (6732): 113--14. \url{https://doi.org/10.1038/20094}.

\bibitem[\citeproctext]{ref-ramachandran2007}
Ramachandran, V. 2007. \emph{3 Clues to Understanding Your Brain}. \url{https://www.ted.com/talks/vs_ramachandran_3_clues_to_understanding_your_brain}.

\bibitem[\citeproctext]{ref-cdchospitalization}
\emph{Rates of Laboratory-Confimed COVID-19 Hospitalizations by Vaccination Status}. 2021. CDC. \url{https://covid.cdc.gov/covid-data-tracker/\#covidnet-hospitalizations-vaccination}.

\bibitem[\citeproctext]{ref-richardson2019}
Richardson, T., and R. T. Gilman. 2019. {``Left-Handedness Is Associated with Greater Fighting Success in Humans.''} \emph{Scientific Reports} 9 (1): 15402. \url{https://doi.org/10.1038/s41598-019-51975-3}.

\bibitem[\citeproctext]{ref-stephens2020}
Stephens, R., and O. Robertson. 2020. {``Swearing as a Response to Pain: Assessing Hypoalgesic Effects of Novel "Swear" Words.''} \emph{Frontiers in Psychology} 11: 643--62.

\bibitem[\citeproctext]{ref-stewart2014}
Stewart, E. H., B. Davis, B. L. Clemans-Taylor, B. Littenberg, C. A. Estrada, and R. M. Centor. 2014. \emph{Rapid Antigen Group a Streptococcus Test to Diagnose Pharyngitis: A Systematic Review and Meta-Analysis}. 9 (11). \url{https://doi.org/10.1371/journal.pone.0111727}.

\bibitem[\citeproctext]{ref-stroop1935}
Stroop, J. R. 1935. {``Studies of Interference in Serial Verbal Reactions.''} \emph{Journal of Experimental Psychology} 18: 643--62.

\bibitem[\citeproctext]{ref-subach2022}
{Subach, et al, A.} 2022. {``Foraging Behaviour, Habitat Use and Population Size of the Desert Horned Viper in the Negev Desert.''} \emph{Soc.Open Sci} 9.

\bibitem[\citeproctext]{ref-sulheim2017}
Sulheim, S., A. Ekeland, I. Holme, and R. Bahr. 2017. \emph{Helmet Use and Risk of Head Injuries in Alpine Skiers and Snowboarders: Changes After an Interval of One Decade}. 51 (1): 44--50. \url{https://doi.org/10.1136/bjsports-2015-095798}.

\bibitem[\citeproctext]{ref-titanic}
\emph{Titanic}. n.d. \url{http://www.encyclopedia-titanica.org}.

\bibitem[\citeproctext]{ref-covidvaccinetracker}
\emph{US COVID-19 Vaccine Tracker: See Your State's Progress}. 2021. Mayo Clinic. \url{https://www.mayoclinic.org/coronavirus-covid-19/vaccine-tracker}.

\bibitem[\citeproctext]{ref-usepa2020}
US Environmental Protection Agency. n.d. \emph{Air Data -- Daily Air Quality Tracker}. \url{https://www.epa.gov/outdoor-air-quality-data/air-data-daily-air-quality-tracker}.

\bibitem[\citeproctext]{ref-wahlstrom2014}
{Wahlstrom, et al, K.} 2014. {``Examining the Impact of Later School Start Times on the Health and Academic Performance of High School Students: A Multi-Site Study.''} \emph{Center for Applied Research and Educational Improvement}.

\bibitem[\citeproctext]{ref-watson2015}
{Watson, et al., N.} 2015. {``Recommended Amount of Sleep for a Heathy Adult: A Joint Consensus Statement of the American Academy of Sleep Medicine and Sleep Research Society.''} \emph{Sleep} 38(6).

\bibitem[\citeproctext]{ref-Weiss1988}
Weiss, R. D. 1988. {``Relapse to Cocaine Abuse After Initiating Desipramine Treatment.''} \emph{JAMA} 260(17).

\bibitem[\citeproctext]{ref-navajo2011}
\emph{Welcome to the Navajo Nation Government: Official Site of the Navajo Nation}. 2011.\href{\%20Retrieved\%20from\%20https://www.navajo-nsn.gov/.}{Retrieved from https://www.navajo-nsn.gov/.}

\bibitem[\citeproctext]{ref-wilson2016}
Wilson, Woodruff, J. P. 2016. {``Vertebral Adaptations to Large Body Size in Theropod Dinosaurs.''} \emph{PLoS ONE} 11(7).

\end{CSLReferences}

\end{document}
